### PR TITLE
Collected small fixes and updates for the next patch release

### LINKED ISSUE #1927: [BUG] Compatibility check fails for USER-INTEL kspace when using restart files and hybrid pair styles.
**Summary**

Using the USER-INTEL kspace requires a compatible pair style. Currently, LAMMPS fails with a "ERROR: Intel styles for kspace require intel pair style.", when using pair_style hybrid and read_restart, even though no such errors are present when using a data file or making a system from scratch.

**LAMMPS Version and Platform**

Latest LAMMPS version (33996d9bac98d4bf2b852531a93ebe495b584d7f). Compiled with intel version 18.0.2 20180210 using Makefile.intel_cpu_intelmpi.

**Steps to Reproduce**

First, create a simple restart (and data) file for a system with hybrid pair with the -sf intel argument. Note that no errors are produced.
```
units real
atom_style charge

region box block -30 30 -30 30 -30 30

create_box 1 box

pair_style hybrid/overlay lj/cut/coul/long 14 10 morse 10
kspace_style pppm 1e-6

mass 1 100
create_atoms 1 single 0 0 -1
create_atoms 1 single 0 0  1
set atom 1 charge  1
set atom 2 charge -1

pair_coeff 1 1 lj/cut/coul/long 1 1
pair_coeff 1 1 morse 1 1 1

run 0

write_data data.sys
write_restart restart.sys
```

LAMMPS errors out when trying to use the previously constructed restart file when executing with the -sf intel argument.
```
units real
atom_style charge
kspace_style pppm 1e-6

# this doesn't work
read_restart restart.sys
pair_coeff 1 1 lj/cut/coul/long 1 1
pair_coeff 1 1 morse 1 1 1
run 0

# this works
#pair_style hybrid/overlay lj/cut/coul/long 14 10 morse 10
#read_data data.sys
#pair_coeff 1 1 lj/cut/coul/long 1 1
#pair_coeff 1 1 morse 1 1 1
#run 0

# this also works
#read_restart restart.sys
#pair_style hybrid/overlay lj/cut/coul/long 14 10 morse 10
#pair_coeff 1 1 lj/cut/coul/long 1 1
#pair_coeff 1 1 morse 1 1 1
#run 0
```
The error can be avoided by using a data file or redefining pair styles after read_restart.

**Expected Behavior**

LAMMPS should correctly detect the compatible pair style when using read_restart.

**Actual Behavior**

Currently, LAMMPS produces the following error:

> ERROR: Intel styles for kspace require intel pair style. (../fix_intel.cpp:551)

**Further Information, Files, and Links**

This issue is related to #1808, which was fixed in PR #1817. I think that read_restart is calling Force::new_pair, which is trying and failing to find a hybrid/overlay/intel style.

### LINKED ISSUE #1935: [BUG] Out of range atoms - cannot compute PPPM with triclinic box and user-intel
**Summary**
There seems to be a bug with pppm/intel and triclinic boxes. Attached is a tar.gz file containing two files, a simple input deck (PEEK0313PCFFTrS0.in) that reproduces the error and the data file (PEEK0313PCFFEq2S0.dat) the input script reads in.

The script reads in an orthogonal data file containing 5 PEEK molecules for a total of 170 atoms. The system has been equilibrated for 200 ps after a 20 Angstrom/ns densification to the bulk density of PEEK 1.30 g/cc.

The simulation is run with the command line arguments "-pk intel 0 omp 2 -sf intel". After the read_data command, the simulation is run for 0 time steps and then the box is changed to a triclinic box (with 0 tilt) and the atoms remapped. The simulation is run again for 0 time steps. The purpose of this is to compare the energies between orthogonal and triclinic with zero tilts. The error occurs at the second run command before the 0 time step thermo is printed. The error is "Out of range atoms - cannot compute PPPM (../pppm_intel.cpp:405)".  

**LAMMPS Version and Platform**
3 Mar 2020, Linux Mint 19.3 (Ubuntu 18.04)

**Expected Behavior**
The energies before and after the change from orthogonal to triclinic should be the same. Also, out of range atoms - cannot compute PPPM errors should not occur when running with user-intel.

**Actual Behavior**
Out of range atoms - cannot compute PPPM errors when running with "-pk intel 0 omp 2 -sf intel". Running the simulation without the Intel package command line arguments does not give any errors. However, the thermo values at each run command (orthogonal vs triclinic) are different. Below are the differences (second run minus first run values):

diff in Step: 0.0
diff in v_Time: 0.0
diff in Temp: 0.0
diff in Press: 0.029999999998835847
diff in TotEng: 0.0006000000000767614
diff in KinEng: 0.0
diff in PotEng: 0.0007000000000516593
diff in E_pair: 0.0007000000000516593
diff in E_bond: 0.0
diff in E_angle: 0.0
diff in E_dihed: 0.0
diff in E_impro: 0.0
diff in E_long: -0.9972000000000065
diff in Lx: 0.0
diff in Ly: 0.0
diff in Lz: 0.0
diff in Density: 0.0

**Steps to Reproduce**
Run PEEK0313PCFFTrS0.in with "-pk intel 0 omp 2 -sf intel" with a LAMMPS binary built with user-intel to observe out of range atoms error. Run PEEK0313PCFFTrS0.in without "-pk intel 0 omp 2 -sf intel" to observe the energy difference.

[triclinic_pppm_user_intel.tar.gz](https://github.com/lammps/lammps/files/4330869/triclinic_pppm_user_intel.tar.gz)

### PR DESCRIPTION
**Pull request by akohlmey**
**Summary**

This pull request combines multiple small changes for the next patch release.

**Related Issues**

Closes #1927 
Closes #1935 

**Author(s)**

Axel Kohlmeyer (Temple U)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

No known issues.

**Implementation Notes**

This PR contains the following individual changes:
- fix bug in hybrid pair styles when reading restart files with active suffix. See issue #1927 
- some cleanups and consistency improvements in MESSAGE package code
- make forward declaration in `kim_init` consistent with the KIM API
- make pppm/intel call some functions from plain pppm in case of a triclinic cell. That will reduce performance, but otherwise avoid unexpected out-of-range errors (see #1935) and keeps us from flagging pppm/intel as not supporting triclinic cells at all.

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

### CODE REVIEW

File: src/COLLOID/pair_lubricate.cpp [hunk 1]
```diff
@@ -142,7 +142,7 @@ void PairLubricate::compute(int eflag, int vflag)
     Ef[2][2] = h_rate[2]/domain->zprd;
     Ef[0][1] = Ef[1][0] = 0.5 * h_rate[5]/domain->yprd;
     Ef[0][2] = Ef[2][0] = 0.5 * h_rate[4]/domain->zprd;
-    Ef[1][2] = Ef[2][1] = 0.5 * h_rate[3]/domain->zprd;
+    Ef[1][2] = Ef[2][1] = 0.5 * h_rate[3]/domain->xprd;
```
Comment (sjplimp) [inline src/COLLOID/pair_lubricate.cpp]: Not clear on why this change is correct.

Comment (akohlmey) [reply src/COLLOID/pair_lubricate.cpp]: @sjplimp you are correct. I was overeager and too careless to apply this change. It clearly contradicts the comments above this code section. I have reverted this change from the branch and will wait how the issue will be resolved before adding it again.
