### PR TITLE
Collected small fixes and updates

### LINKED ISSUE #4930: [BUG] Error in reading restart files with dihedral_style fourier when KOKKOS is used
**Summary**

When reading a restart file using the ```read_restart```  command of a simulation in which ```dihedral_style fourier``` is used, LAMMPS exits with an error if KOKKOS is used. The error does not occur with e.g. ```dihedral_style harmonic``` and it does also not occur when KOKKOS is disabled. 

**LAMMPS Version and Platform**
LAMMPS (11 Feb 2026)
KOKKOS mode with Kokkos version 5.0.2 is enabled

Build through CMake with:
```cmake -DCMAKE_BUILD_TYPE=Release -DPKG_ML-PACE=ON -DPKG_MANYBODY=yes -DPKG_KSPACE=yes -DPKG_MOLECULE=yes -DPKG_EXTRA-MOLECULE=yes DPKG_OPENMP=yes -DPKG_KOKKOS=yes -D Kokkos_ARCH_ZEN4=yes -D Kokkos_ARCH_HOPPER90=yes -D Kokkos_ENABLE_CUDA=yes -D FFT_KOKKOS=FFTW3 ../cmake```

Operating System: Rocky Linux 9.7 (Blue Onyx)
OpenMPI Version: 5.0.3
FFTW Version: 3.3.10

GPU: NVIDIA H200
GPU Driver Version: 580.126.09
CUDA Version: 12.6

**Expected Behavior**

A command [1] like ```lmp -k on g 1 -sf kk -restart2info restart.test -pk kokkos neigh half newton on``` is expected to provide information about the restart file after reading it. The reading of the restart file is identical to ```read_restart test.in``` used within an input script.
A similar command [2] without using KOKKOS is ```lmp -restart2info restart.test```.

**Actual Behavior**

The first command [1] results in an error. The output reads: 

```
LAMMPS (11 Feb 2026)
KOKKOS mode with Kokkos version 5.0.2 is enabled
  using double precision
  using view layout = legacy
  will use up to 1 GPU(s) per node
  using 1 OpenMP thread(s) per MPI task
Reading restart file ...
  restart file = 11 Feb 2026, LAMMPS = 11 Feb 2026
  restoring atom style full/kk from restart
  orthogonal box = (0 0 0) to (100 100 100)
  1 by 1 by 1 MPI processor grid
  restoring pair style lj/cut/coul/cut/kk from restart
  restoring bond style harmonic/kk from restart
  restoring angle style harmonic/kk from restart
  restoring dihedral style fourier/kk from restart
corrupted size vs. prev_size
Aborted (core dumped)
```

When using other ```dihedral_style``` types, reading of the restart file works as expected. Also ```dihedral_style fourier``` when KOKKOS is not used (see command [2]) works as expected.

**Steps to Reproduce**

A minimal example that should reproduce the error is the following. Download the attached files mol.txt and in.txt to start. 

1. Run ```mpirun -np 1 lmp -k on g 1 -sf kk -in in.txt -pk kokkos neigh half newton on``` to create a restart file for a small octane molecule (structure provided in mol.txt). The input file ```in.txt``` parameterizes the molecule using ```dihedral_style fourier```.

2. Then run ```mpirun -np 1 lmp -k on g 1 -sf kk -restart2info restart.test -pk kokkos neigh half newton on``` to observe the error. When running ```mpirun -np 1 lmp -restart2info restart.test``` the error should not occur. 

3. I also checked ```dihedral_style harmonic``` instead. Some arbitrary test parameters are also provided in the input file. To test this dihedral style, in the input script comment fourier dihedral style parameters out and harmonic dihedral style parameter in. Then repeat steps 1 and 2.

Note that the error also occurs when executing ```read_restart restart.test``` within any input file.

**Further Information, Files, and Links**

[in.txt](https://github.com/user-attachments/files/26308607/in.txt)
[mol.txt](https://github.com/user-attachments/files/26308606/mol.txt)

### PR DESCRIPTION
**Pull request by akohlmey**
**Summary**

This pull request combines multiple small changes and fixes

**Related Issue(s)**

Fixes #4930 

**Author(s)**

Axel Kohlmeyer, Temple U

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Artificial Intelligence (AI) Tools Usage**

The code for computing superellipsoid normals and rotating the triangle meshes for ellipsoids and superellipsoids was generated by Claude Opus 4.6

**Backward Compatibility**

Binary restart files have changed with dihedral style fourier.

**Implementation Notes**

The following individual changes are included:
- relax epsilon on test for portability to ARM64
- implement superellipsoid normals for ellipsoid particles with dump image
- rotate initial triangle mesh used for ellipsoids and superellipsoids to that
  the principal axes pass approximately through triangle centers and thus appear
  less "pointy" with lower refinement levels
- updates and corrections suggested by clang static code analysis
- fix issues reported by coverity scan static code analysis
- bugfix for restarting dihedral style fourier with KOKKOS enabled
- follow LAMMPS programming conventions more closely in recently added code
- mention superellipsoids in extended particle and visualization howtos

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.

### CODE REVIEW

**Comment by akohlmey** [comment]
@sjplimp @jtclemm @jibril-b-coulibaly @JBil8 This adds some information about visualizing superellipsoids with dump image and a few example images to the visualization howto. Please let me know if you have something else that you would like to highlight.

**Comment by akohlmey** [comment]
> @sjplimp @jtclemm @jibril-b-coulibaly @JBil8 This adds some information about visualizing superellipsoids with dump image and a few example images to the visualization howto. Please let me know if you have something else that you would like to highlight.

FYI, if you want to interactively experiment with the visualization settings, I have just uploaded LAMMPS-GUI packages to https://download.lammps.org/testing/ that include a LAMMPS shared library with the latest changes from this branch. For example, you can open the example inputs and then open the image viewer and it should show a low resolution version of the initial system and then you can modify it with the options in "Atoms/Bonds" dialog and "Global" dialog. https://lammps-gui.lammps.org/visualization.html

Please let me know if you run into any issues or get unexpected crashes or see discrepancies between the software and the documentation (both LAMMPS-GUI and LAMMPS).

The documentation of the develop branch (minus the changes in this pull request) is available online here https://docs.lammps.org/latest/
A PDF version (including the changes from this branch) is also in the testing repository.

File: src/KOKKOS/dihedral_fourier_kokkos.cpp [hunk 1]
```diff
@@ -343,31 +341,23 @@ void DihedralFourierKokkos<DeviceType>::operator()(TagDihedralFourierCompute<NEW
...
 
 template<class DeviceType>
-void DihedralFourierKokkos<DeviceType>::allocate_kokkos()
+void DihedralFourierKokkos<DeviceType>::allocate()
 {
+  DihedralFourier::allocate();
+
   int n = atom->ndihedraltypes;
 
-  if (!allocated_kokkos) {
```
Comment (akohlmey) [inline src/KOKKOS/dihedral_fourier_kokkos.cpp:350]: @stanmoore1 this seems to be rolling back some changes of yours and closely aligning the code with what is done in dihedral style harmonic. This seems to solve the problem in issue #4930 but it is not clear to me what problem your changes were addressing and whether I am just replacing one issue with another.

Can you please have a look?

Comment (akohlmey) [reply src/KOKKOS/dihedral_fourier_kokkos.cpp:350]: Nevermind, I had to back this out since it failed the force style tests. But in the process I found the real cause and the fix: https://github.com/lammps/lammps/pull/4929/changes/9b8fba600105df5e8748579188d2d2a5ab998175

**Comment by akohlmey** [comment]
@sjplimp @jtclemm @jibril-b-coulibaly @JBil8 I've improved the visual quality of ellipsoids and superellipsoids with lower mesh refinement by rotating the triangle mesh so that the principal axes will pass through a triangle face (near the center) instead of an edge or a corner. 

P.S.: This is for a (2,1,1) or (1,2,1) or (1,1,2) shape with only 48 triangles
refinement level 2)
imageimage

**Review by sjplimp — APPROVED** [review]

**Review by jtclemm — APPROVED** [review]
I like the superellipsoid zoo image & demo, very helpful

Edit: I still haven't had time to dig into any of the new rendering features of dump image, but one day
