### PR TITLE
Test program updates and related changes

### LINKED ISSUE #2184: [BUG] Kokkos crashing due to AtomVec changes
**Summary**

I'm seeing 100% failure of the Kokkos regression tests due to recent changes in AtomVec. 

```
#0  0x0000003303a324f5 in raise () from /lib64/libc.so.6
#1  0x0000003303a33cd5 in abort () from /lib64/libc.so.6
#2  0x0000003303a70417 in __libc_message () from /lib64/libc.so.6
#3  0x0000003303a75e5e in malloc_printerr () from /lib64/libc.so.6
#4  0x0000003303a78cad in _int_free () from /lib64/libc.so.6
#5  0x0000000000482fe5 in LAMMPS_NS::Memory::sfree(void*) () at ../memory.cpp:109
#6  0x0000000000480098 in void LAMMPS_NS::Memory::destroy<int>(int*&) () at ../memory.h:79
#7  0x000000000066f5e8 in LAMMPS_NS::AtomVec::~AtomVec() () at ../atom_vec.cpp:106
#8  0x000000000063f9b3 in LAMMPS_NS::AtomVecKokkos::~AtomVecKokkos() () at ../atom_vec_kokkos.h:37
#9  0x000000000063fb27 in LAMMPS_NS::AtomVecAtomicKokkos::~AtomVecAtomicKokkos() ()
    at ../atom_vec_atomic_kokkos.h:33
#10 0x000000000063fb56 in LAMMPS_NS::AtomVecAtomicKokkos::~AtomVecAtomicKokkos() ()
    at ../atom_vec_atomic_kokkos.h:33
#11 0x000000000061a298 in LAMMPS_NS::Atom::create_avec(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, char**, int) () at ../atom.cpp:596
#12 0x00000000004111eb in LAMMPS_NS::Input::atom_style() () at ../input.cpp:1412
#13 0x000000000040ba05 in LAMMPS_NS::Input::execute_command() () at ../input.cpp:797
#14 0x00000000004092d1 in LAMMPS_NS::Input::file() () at ../input.cpp:230
#15 0x0000000000407a64 in main ()
```

**LAMMPS Version and Platform**

Latest Master

**Steps to Reproduce**

Run any input deck with Kokkos enabled

### PR DESCRIPTION
**Pull request by akohlmey**
**Summary**

This add tests for atom styles and fixes some issues detected by those tests.

**Related Issues**

This fixes a memory leak introduced by #2180 
Also fixes #2184 

**Author(s)**

Axel Kohlmeyer, Temple U

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

No known issues

**Implementation Notes**

The deallocation of common per-atom arrays had to be put back to the Atom class destructor to make replicate work without causing memory leaks elsewhere.

In addition the following changes are included:
- add support for using LeakSanitizer (subset of AddressSanitizer with no performance impact)
- add support to use valgrind's memcheck tool automatically with `ctest` through CMake.
- add customized valgrind suppression files for OpenMPI, OpenMP and Python.
- make sure substyle pointers for bond/angle lists are initialized to NULL in hybrid styles.
- zero out local per-thread storage in hybrid angle/bond styles with threads enabled to avoid accessing uninitialized data when using multi-threaded substyles.
- add some missing linefeed characters in `{fmt}` formatted strings
- make more use of `std::string` and `{fmt}` and `utils::logmesg()`
- add `utils::split_words()` convenience function for splitting command lines into a vector of strings with support for single/double quotes etc.
- parse `TEST_ARGS` environment variable directly instead of using `cmake -E` script wrapper so memory checking with ctest works properly
- add a couple of unittest yaml files for SNAP pair styles
- improve and expand tester tool for atom styles

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [x] Suitable tests have been added to the unittest tree.

### CODE REVIEW

File: src/atom_vec.cpp [hunk 1]
```diff
@@ -2572,13 +2562,13 @@ void AtomVec::create_method(int nfield, Method *method)
...
 void AtomVec::init_method(Method *method)
 {
-  method->pdata = NULL;
-  method->datatype = NULL;
-  method->cols = NULL;
-  method->maxcols = NULL;
-  method->collength = NULL;
-  method->plength = NULL;
-  method->index = NULL;
+  method->pdata = nullptr;
```
Comment (sjplimp) [inline src/atom_vec.cpp:2565]: why this change?  what's wrong with NULL?

Comment (akohlmey) [reply src/atom_vec.cpp:2565]: Technically speaking `NULL` is a character with the value 0, `nullptr` is a pointer. Having a pointer vs. non-pointer missmatch with `nullptr` will not create a compiler error or warning (depending on compiler and settings) which is helpful to detect incorrect use, while `NULL` will not. We are going to replace those gradually throughout the code. ... or I can do one big pull request that just changes this globally, if you prefer. This is one of the features of C++11 that is helpful to detect incorrect use at compile time. another would be to use "override" to detect unintentionally overloaded virtual functions.

Comment (akohlmey) [reply src/atom_vec.cpp:2565]: grrr had to update the message on github. one "not" too many.
