### PR TITLE
Fix Inconsistent syntax for dump_modify triclinic/general

### LINKED ISSUE #4151: [BUG] Inconsistent syntax for dump_modify triclinic/general
**Summary**

Applying the `dump_modify 1 triclinic/general` setting should work identically for both the `atom` and the `custom` dump style. Right now, one needs to set: `dump_modify 1 triclinic/general` when dump 1 references an `atom` dump style and `dump_modify 1 triclinic/general yes` when using a `custom` dump style.

**LAMMPS Version and Platform**

- LAMMPS development branch (commit 628531dadb) (LAMMPS (17 Apr 2024))
- Windows 11 (22631.3527)
- `cl.exe --version Microsoft (R) C/C++ Optimizing Compiler Version 19.39.33522 for x64`

**Expected Behavior**

```
dump               3 all atom 100 3.dump 
dump_modify   3 triclinic/general yes
```
should set the dump to output in `triclinic/general` format.

This would match the behavior for the custom dump style:
```
dump               1 all custom 100 1.dump id type x y z
dump_modify   1 triclinic/general yes
``` 

And should work as stated in the [manual](https://docs.lammps.org/dump_modify.html):
> triclinic/general arg = yes or no
> ...
> The triclinic/general keyword only applies to the dump atom and custom styles. It can only be used with a value of yes if the simulation box was created as a general triclinic box. See the [Howto_triclinic](https://docs.lammps.org/Howto_triclinic.html) doc page for a detailed explanation of orthogonal, restricted triclinic, and general triclinic simulation boxes.

**Actual Behavior**

When using:
```
dump               3 all atom 100 3.dump 
dump_modify   3 triclinic/general yes
```
in a lammps input script, I get the following error message:

> ERROR: Unknown dump_modify keyword: yes (D:\Work\lammps\src\dump.cpp:1320)
Last command: dump_modify   3 triclinic/general yes

However changing the command to 
```
dump               3 all atom 100 3.dump 
dump_modify   3 triclinic/general
```
seems to work as intended.

**Steps to Reproduce**

The following lammps input script can be used to reproduce the bug:

```
lattice       custom 1.1 a2 0.0 0.5 0.5 a3 0.5 0.0 0.5 a1 0.5 0.5 0.0 basis 0.0 0.0 0.0 triclinic/general
create_box    1 NULL 0 1 0 1 0 1
create_atoms  1 box
mass          * 1.0

pair_style    lj/cut 1.2
pair_coeff    * * 1.0 1.0

neighbor      0.0 bin

dump               1 all custom 100 1.dump id type x y z
dump_modify   1 triclinic/general yes

dump               3 all atom 100 fcc.primitive.general.atom.dump 
dump_modify   3 triclinic/general yes

run           0
```

### PR DESCRIPTION
**Pull request by nnn911**
**Summary**

Applying the `dump_modify 1 triclinic/general` setting should work identically for both the atom and the custom dump style. Right now, one needs to set: `dump_modify 1 triclinic/general` when dump 1 references an atom dump style and `dump_modify 1 triclinic/general yes` when using a custom dump style.

This pr fixes this inconsistent syntax and enforces the verbose `dump_modify 1 triclinic/general yes`

**Related Issue(s)**

Fixes #4151 

**Author(s)**

Daniel Utt (utt@ovito.org)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Yes, this will break backwards comparability with the recently introduced `dump_modify 1 triclinic/general yes` setting. However, it will lead to matching syntax for `custom` and `atomic` dump formats.

One could implement this as a non-breaking change, however, this might lead to confusion on the user side with `dump_modify 1 triclinic/general` and `dump_modify 1 triclinic/general yes` both being valid syntax.

The proposed change enforces a more verbose and clear syntax.  

**Implementation Notes**

Mirror the implementation of the `modify_param` parsing used in `dump_custom.cpp:1765` in `dump_atom.cpp`. 

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

### CODE REVIEW

File: src/dump_atom.cpp [hunk 1]
```diff
@@ -166,11 +166,11 @@ int DumpAtom::modify_param(int narg, char **arg)
...
 
   if (strcmp(arg[0],"triclinic/general") == 0) {
-    triclinic_general = 1;
+    if (narg < 2) error->all(FLERR,"Illegal dump_modify command");
+    triclinic_general = utils::logical(FLERR,arg[1],false,lmp);
     if (triclinic_general && !domain->triclinic_general)
-      error->all(FLERR,"Dump_modify triclinic/general cannot be used "
-                 "if simulation box is not general triclinic");
-    return 1;
+      error->all(FLERR,"Dump_modify triclinic/general invalid b/c simulation box is not");
```
Comment (sjplimp) [inline src/dump_atom.cpp]: Can you use the old error message from dump_atom.cpp here and also in dump_custom.cpp ?  I think it is more clear than this one.

**Comment by sjplimp** [comment]
@nnn911 thanks for catching this inconsistency

File: src/dump_atom.cpp (hunk 1 above)
Comment (nnn911) [reply src/dump_atom.cpp]: I Updated both messages. The old one is definitely more useful to the user.

**Review by sjplimp — APPROVED** [review]

**Comment by sjplimp** [comment]
BTW, there are a couple other commands for this, like write_data where the syntax for the option is simply triclinic/general.
No 2nd arg for yes or no.  The rationale is to use yes/no when the command could be used to turn it on or off, as is the case with dump_modify.
