### PR TITLE
Collected small changes and bug fixes

### LINKED ISSUE #3070: [BUG] Segmentation fault with package GPU when `fix nve` group is not `all`
**Summary**

`fix nve` results in an immediate segmentation fault when the GPU package is used and the integration group is other than `all`.
`fix nvt` and `fix npt` seem unaffected.
Running LAMMPS on CPU is not affected.

**LAMMPS Version and Platform**

The bug has been encountered on `lammps-stable_29Sep2021` and `lammps-stable_29Sep2021_update1`.
Version `lammps-stable_3Mar2020` runs the same script without errors.

Platform:
OpenSUSE Leap 15.3
Linux 5.3.18-59.37-default x86_64
AMD Ryzen Threadripper 1900X 8-Core Processor
NVidia 1070 card
Driver Version: 495.29.05    CUDA Version: 11.4

**Expected Behavior**

Scripts with `fix nve/gpu` on non-`all` group running without issues.

**Actual Behavior**

Scripts with `fix nve/gpu` on non-`all` group crash with segmentation fault immediately when `run` command is invoked.

**Steps to Reproduce**

Start LAMMPS built with GPU library with
```
lammps -pk gpu 1 -sf gpu -in in.melt_broken
```
on the script in the gist below

**Further Information, Files, and Links**

script gist:
https://gist.github.com/vvpisarev/acf4954b3d4659dfbb9d81c3c5db6616

### LINKED ISSUE #3074: [BUG] Issues with CD-EAM pair style
**Summary**

There are several bugs in the CD-EAM pair style. This results in incorrect behavior while running multiple simulations from one input file. 
The summary of the bugs is below:
1) The main EAM pair style constructs the index for spline tables as `m = MAX(1,MIN(m,nrho-1))`, while CD-EAM pair style uses  `index.m = index.m <= (nrho-1) ? index.m : (nrho-1)`. The case of `m=0` is undefined in the `PairEAM::interpolate` function, so sometimes CD-EAM functions read garbage from the zero index.
2) The variable `D_i` is not initialized (line 301, MANYBODY/pair_eam_cd.cpp) and we have undefined behavior at line 391.
3) It is necessary to add  `&& rho[j] != 0.0` at line 357 of pair_eam_cd.cpp (like in the `if` condition at line 305). The `ASSERT()` macro does nothing in the current implementation.
I attach the file [patch.txt](https://github.com/lammps/lammps/files/7801872/patch.txt) to fix these isssues. There are also small improvements for better readability of the code. The `ASSERT()` macro was used in the original USER-CD-EAM/pair_cdeam.cpp for debugging purposes. This code is completely lost in the current version. I believe it is safe to remove all the `ASSERT()` calls from the code.

**LAMMPS Version and Platform**

The bugs exist since the first implementation of the USER-CD-EAM package. They are also exist in the latest pair_cd_eam version.

**Expected Behavior**

The same result in single and loop mode simulations.

**Actual Behavior**

The incorrect energies while running LAMMPS in loop mode with `pair_style eam/cd`.

**Steps to Reproduce**
[The simple script to compute the diatom energy vs r.](https://github.com/lammps/lammps/files/7801689/fecr.input.txt)
FeCr.cdeam is from lammps/potentials directory.
Please observe the incorrect energy at 4.2 Å.

### PR DESCRIPTION
**Pull request by akohlmey**
**Summary**

The pull request combines multiple small changes and bug fixes that do not warrant a pull request of their own.

**Related Issue(s)**

Fixes #3070
Fixes #3074 
Closes #3076 

**Author(s)**

Axel Kohlmeyer, Temple U

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

No known issues

**Implementation Notes**

The following individual changes are included:
- fix segfault in fix nve/gpu when the group is not "all" but there is only 1 atom type
- fix bugs in eam/cd pair style reported in issue #3074 
- correct format string used in `Error::one()` to output the last command used
- add missing table elements for linear interpolation style tables for bonds and angles from extrapolation. Alternate fix for the issue from #3076

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

### CODE REVIEW

File: src/MANYBODY/pair_eam_cd.cpp [hunk 1]
```diff
@@ -502,22 +490,19 @@ void PairEAMCD::read_h_coeff(char *filename)
...
-                                   filename);
+      error->one(FLERR,"Cannot open EAMCD potential file {}", filename);
 
     // h coefficients are stored at the end of the file.
     // Skip to last line of file.
 
-    while (fgets(nextline, MAXLINE, fptr) != nullptr) {
-      strcpy(line, nextline);
-    }
+    while (fgets(line[toggle], MAXLINE, fptr) != nullptr)
```
Comment (akohlmey) [inline src/MANYBODY/pair_eam_cd.cpp:502]: @rbberger please have a look at this change. This avoids the additional copy of the line by alternating between two buffers, but I am not certain whether doing it this way is obvious enough. I should probably add some comment. We could also just allocate two buffers with `new` and swap them, for example. Might be easier to read. This was just the first thought that came to me based on the existing code.

Comment (akohlmey) [reply src/MANYBODY/pair_eam_cd.cpp]: New version is implemented as discussed. had to deal with a minor complication (`fread()` does not 0-terminate) but it now works. It also was tested successfully with a potential file lacking the final newline.

**Review by stanmoore1 — APPROVED** [review]

**Review by sjplimp — APPROVED** [review]
