### PR TITLE
Fix occasional bug in neighbor list build for triclinic geometries due to round off

### LINKED ISSUE #2759: [BUG] in rare cases roundoff makes neighbor list fail to find pairs
**Summary**

If atom initial positions are outside the [0..1] scaled coordinate range, LAMMPS's wrapping can break the symmetry between local and ghost atom pairs, and that makes the neighbor lists's spatial ordering reject both times it checks the pair of atoms that should be neighbors.  See also more detailed discussion at [this matsci.org thread](https://matsci.org/t/apparently-inconsistent-forces-before-after-dump/36305/28).

**LAMMPS Version and Platform**

`LAMMPS (8 Apr 2021)`

CentOS 7 on an Intel CPU, gcc 10.3.0, compiled with -O0 or -O1.  It also appears to be the same for gcc 7.3.

**Expected Behavior**

When running attached input script, a neighbor list containing one pair of atoms (i.e. output contains `Total # of neighbors = 1`)

**Actual Behavior**

output contains `Total # of neighbors = 0`

**Steps to Reproduce**

`lmp_serial -in two_atoms.in | grep 'Total # of neigh'`

**Further Information, Files, and Links**

[two_atoms.in.gz](https://github.com/lammps/lammps/files/6444471/two_atoms.in.gz)

### PR DESCRIPTION
**Pull request by sjplimp**
**Summary**

As described in issue #2759 and [this matsci.org thread](https://matsci.org/t/apparently-inconsistent-forces-before-after-dump/36305/28), triclinic (non-orthogonal box) models can construct their neighbor list incorrectly in rare instances:

(a) triclinic geometry
(b) I,J atom pairs which straddle simulation box boundary
(c) systems with atoms on a perfect lattice (e.g. the initial config)
(d) binned half neighbor list with newton on

The problem is due to coordinate transformations for owned and ghost atoms from box coords to reduced (lambda) coords and back again, which occurs before a neighbor list is built.  This can (rarely) result in a coordinate of a ghost atom outside the simulation box being epsilon different than a coordinate of the same atom inside the box due to periodic box offsets being added, even when they would ideally be identical.  E.g. in an orthogonal box the Y coordinate will be identical for a ghost atom that straddles the periodic X boundary, but for triclinic its back-and-forth numerical transformation can make them different by epsilon due to round-off.  The neighbor list build method for triclinic geometries assumed binning and exact comparisons of coords would be consistent for an I,J and J,I pair to consistently exclude exactly one of them.

The signature of the bug is that the I.J pair is included in the neighbor list 0 or 2 times, rather than 1, leading to incorrect energy and forces.

The remedy in this PR is twofold.  For triclinic, change the stencil of bins to be a full stencil rather than a half stencil (in the last dimension).  And second, also for triclinic, change the logic in the neighbor list build (binned or Nsq) to only rely on the I,J atom IDs and in the special case (cutoff > box size) where the IDs of the I,J atoms are the same, to rely on large differences in coordinates rather than exact coordinates to make the decision to include/exclude the two I,J pairs consistently.

**Related Issue(s)**

Fixes #2759

**Author(s)**

Steve

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

**Implementation Notes**

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Review by stanmoore1 — CHANGES_REQUESTED** [review]
I need to port this to Kokkos too

**Comment by sjplimp** [comment]
@stanmoore1 you should wait, b/c if may not yet be correct, and b/c once it is I will make the same change to several other NPair classes (those with tri or nsq in the name)

**Comment by stanmoore1** [comment]
OK I will wait, I just wanted to make sure it doesn't get merged without Kokkos updates

**Comment by akohlmey** [comment]
@sjplimp @stanmoore1 I have ported the existing changes to OPENMP, but it looks to me as if some more NPair styles need to be adjusted, e.g. the multi and respa variants, which have similar code patterns. I have not looked at INTEL, but it likely needs porting, too, same as KOKKOS. OPENMP was straightforward since the affected code is mostly identical to the non-OPENMP version.

**Comment by sjplimp** [comment]
@akohlmey @stanmoore1 @jtclemm @wmbrownIntel Please take a look at this PR and its changes to a few NPair and NStencil classes to fix a (rare) issue with triclinic geometries.  I believe I have made all the changes needed for vanilla CPU classes, but not for accelerated classes.  At a code level, these are the rules-of-thumb for the code changes:

(a) for binning, the Nstencil class for triclinic needs to by "full" in all dims, because the code can't rely on an atom's bin being consistent for ghost atoms that straddle periodic boundaries - previous the triclinic stencil was half-size in z (or in y for 2d)
(b) for triclinic, the NPair class cannot compare two atoms (owned and ghost) expecting their coords (in some dim) to be identical, instead logic with the atom IDs (itag, jtag) needs to be used, as well as logic that reflects the full stencil
(c) this is not as simple as only checking NStencil and NPair classes with "tri" in their name, b/c some classes are invoked for both orthogonal and triclinic - e.g. NPair Nsq and HalfFull classes - in those cases exact coord compisons can still be used for orthogonal, but (b) needs to be used for triclinic

@akohlmey Leaving the OPENMP changes to you

@stanmoore1 Leaving the KOKKOS changes to you

@jtclemm I made the changes I thought were correct for the "multi" neighbor classes (and also "multi/old") but please check them over - this will also affect your pending PR that refactors these various classes

@wmbrownIntel I looked at the INTEL variants for triclinic but they invoke a tempted class in the parent which appears to be called for both orthogonal and triclinic - so I didn't want to make any changes in the templated method

**Comment by sjplimp** [comment]
@akohlmey This version fixes all the problem cases Identified in the related issue, as well as the MatSci thread

**Comment by akohlmey** [comment]
@stanmoore1 OPENMP seems to be done now.

**Comment by stanmoore1** [comment]
Does this need a check like in ReaxFF to make sure tags are enabled?
```
  if (atom->tag_enable == 0)
    error->all(FLERR,"Pair style reaxff requires atom IDs");
```
i.e. if the user turns off atom ids with `atom_modify id no`?

**Comment by sjplimp** [comment]
yes, good catch - using triclinic will now require tags - I will add that

File: src/nstencil_half_multi_3d_tri.cpp [hunk 1]
```diff
@@ -81,7 +81,7 @@ void NStencilHalfMulti3dTri::create()
       cutsq = cutcollectionsq[icollection][jcollection];
 
       if (flag_half_multi[icollection][jcollection]) {
-        for (k = 0; k <= sz; k++)
+        for (k = -sz; k <= sz; k++)
```
Comment (jtclemm) [inline src/nstencil_half_multi_3d_tri.cpp:84]: While this works, a more consistent method would be to change the logic in `set_stencil_properties()` such that the "same collection" uses a full stencil instead of changing the definition of a half stencil. I.e.:

```
if (cutcollectionsq[i][i] == cutcollectionsq[j][j]) {
        flag_half_multi[i][j] = false; //true;
        bin_collection_multi[i][j] = i;
}
```

Practically, however, this makes no difference. So I can just make this alternate change in the other pull request.

Comment (sjplimp) [reply src/nstencil_half_multi_3d_tri.cpp:84]: agreed - just make the change in the later PR - thanks for checking

**Comment by wmbrownIntel** [comment]
I don't think I can push here, but I put the changes for the intel package: [https://github.com/wmbrownIntel/lammps/tree/triclinic-neighbor-bug](https://github.com/wmbrownIntel/lammps/tree/triclinic-neighbor-bug )

Please let me know if this doesn't work.

**Comment by sjplimp** [comment]
@wmbrownIntel - thanks Mike

**Comment by stanmoore1** [comment]
@sjplimp @akohlmey do we have a canonical test for this issue? I'm having trouble reproducing with the input in https://github.com/lammps/lammps/issues/2759

**Comment by stanmoore1** [comment]
When I run the latest `develop` branch on the CPU with no Kokkos (i.e. without the bugfix in this PR), I see `Total # of neighbors = 1` which is not expected according to https://github.com/lammps/lammps/issues/2759

**Comment by stanmoore1** [comment]
The `two_atoms` test case gives expected behavior on one machine but not another, probably due to roundoff and a different OS/hardware.

**Comment by stanmoore1** [comment]
Everything is passing, including the test cases in https://github.com/lammps/lammps/issues/2759, except the `nemd` example lost atoms with Kokkos CUDA, need to investigate. Also one of the unit tests failed but it looks unrelated to the changes in this PR.

**Comment by akohlmey** [comment]
> Also one of the unit tests failed but it looks unrelated to the changes in this PR.

Yes, that test failure is due to a race condition in OpenMPI as bundled in the Ubuntu 20.04LTS container. It happens very rarely and it is usually sufficient to rerun the group of tests. I just have tried to trigger this.

**Comment by stanmoore1** [comment]
The `nemd` lost atoms on GPU appears to be a false positive or at least I cannot reproduce it outside of Jenkins. I built on the same machine using the exact same commands and it runs fine. It also runs fine on another GPU testbed. Therefore I believe this PR is ready to merge from my POV.

**Comment by stanmoore1** [comment]
Found the bug, testing again.

**Comment by stanmoore1** [comment]
All regression tests pass now, but I'm seeing a slowdown for the chute benchmark on GPU, looking into it.

**Review by stanmoore1 — APPROVED** [review]

**Comment by stanmoore1** [comment]
Performance is restored, ready to merge.
