### PR TITLE
Collected small changes and fixes

### LINKED ISSUE #3854: [BUG] _temper/npt restart index
**Summary**

The command temper/npt is not working as expected is not getting the restart flag "index"  as pointed in the doc page, 
Also it says that it can take a different pressure for each replica, but it seems this is not the case. 

**LAMMPS Version and Platform**

LAMMPS (28 Mar 2023)

**Expected Behavior**
As the manual says for temper/npt the same features as temper applies and also replicas of varying pressure 

**Actual Behavior**

If I put a number in the index flag it gives an error 

**Further Information, Files, and Links**

I have detect in the code that 

line 77   double press_set = utils::numeric(FLERR,arg[6],false,lmp);

line 92  if (narg == 8) my_set_temp = utils::inumeric(FLERR,arg[6],false,lmp);

In line 92 my_set_temp is being assigned to the pressure and not to the index flag, position 6, when it should take position 7, I believe 

I believe this should be changed 

Also I don't see a pressure swap in the code, i might be missing where it is . Anyway  if this was not intended this might be explicit in the manual 

Thanks for the help 
Matias

### PR DESCRIPTION
**Pull request by akohlmey**
**Summary**

This pull request combines multiple small fixes and changes

**Related Issue(s)**

fixes #3854

**Author(s)**

Axel Kohlmeyer, Temple U

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

No known issues.

**Implementation Notes**

The following individual changes are included:
- update VIM syntax highlighting for LAMMPS input files
- fix of an off-by-one bug when parsing the optional argument of the temper/npt command
- fixes to address static code analysis issues in selected files
- coding style improvement and code modernization in selected files
- small corrections and style improvements in the manual

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated

### CODE REVIEW

File: src/REPLICA/temper.h [hunk 1]
```diff
@@ -40,8 +40,7 @@ class Temper : public Command {
   int nswaps;                           // # of tempering swaps to perform
   int seed_swap;                        // 0 = toggle swaps, n = RNG for swap direction
   int seed_boltz;                       // seed for Boltz factor comparison
-  int whichfix;                         // index of temperature fix to use
-  int fixstyle;                         // what kind of temperature fix is used
+  class Fix *whichfix;                  // index of temperature fix to use
```
Comment (rbberger) [inline src/REPLICA/temper.h]: Comment outdated. Not an index anymore

**Review by sjplimp — APPROVED** [review]
