### PR TITLE
Collected small changes and bug fixes

### LINKED ISSUE #4476: [BUG] Bug fails on F43
Building [lammps-20250204](https://koji.fedoraproject.org/koji/buildinfo?buildID=2660424) on Fedora 43:
```
  8/431 Test   #8: Utils ...........................................Subprocess aborted***Exception:   0.18 sec
Running main() from gmock_main.cc
[==========] Running 147 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 147 tests from Utils
[ RUN      ] Utils.strdup
[       OK ] Utils.strdup (0 ms)
[ RUN      ] Utils.strsame
[       OK ] Utils.strsame (0 ms)
[ RUN      ] Utils.strcompress
/usr/include/c++/15/bits/basic_string.h:1373: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::reference std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::back() [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; reference = char&]: Assertion '!empty()' failed.
```

### PR DESCRIPTION
**Pull request by akohlmey**
**Summary**

This pull request collects multiple small changes and bug fixes

**Related Issue(s)**

This addresses the issues mentioned in:
https://matsci.org/t/angle-style-cosine-delta-issue/61247
and in:
https://matsci.org/t/bad-termination-killed-by-signal-9-more-than-two-processors-in-the-z-direction/60790/3
Fixes #4476 
Supersedes and thus closes #4478
Supersedes and thus closes #4480

**Author(s)**

Axel Kohlmeyer, Temple U

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Forces and energies for angle style cosine/delta will change

**Implementation Notes**

The following changes are included:
- avoid segmentation fault in fix rigid/small/omp
- correctly compute energy and forces in angle style cosine/delta
- fixes undefined behavior in `utils::strcompress` when the output string becomes empty.
- fixes bug in DPD-BASIC pair styles when their special_lj values are changed with pair_modify pair special as part of a hybrid pair style

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [x] Suitable tests have been added to the unittest tree.

### CODE REVIEW

**Comment by rbberger** [comment]
@akohlmey [b3e75a6](https://github.com/lammps/lammps/pull/4477/commits/b3e75a6f841c1cf783605b0d1bb0a4537b1e947d) is a small change due to failures here: https://koji.fedoraproject.org/koji/taskinfo?taskID=129562933

**Comment by akohlmey** [comment]
> @akohlmey [b3e75a6](https://github.com/lammps/lammps/pull/4477/commits/b3e75a6f841c1cf783605b0d1bb0a4537b1e947d) is a small change due to failures here: https://koji.fedoraproject.org/koji/taskinfo?taskID=129562933

Yup. That is OK. Only when you have to go below 1.0e-10 we have to start worrying, especially with an analytical potential. Those using tabulation are generally more noisy.

File: src/balance.cpp [hunk 1]
```diff
@@ -152,16 +150,15 @@ void Balance::command(int narg, char **arg)
...
       style = XYZ;
+      if (iarg+2 > narg) utils::missing_cmd_args(FLERR,"balance y", error);
       if (strcmp(arg[iarg+1],"uniform") == 0) {
-        if (iarg+2 > narg) error->all(FLERR,"Illegal balance command");
         yflag = UNIFORM;
         iarg += 2;
       } else {
-        if (1 + procgrid[1]-1 > narg)
-          error->all(FLERR,"Illegal balance command");
+        if (1 + procgrid[1]-1 > narg) utils::missing_cmd_args(FLERR,"balance y", error);
```
Comment (jtclemm) [inline src/balance.cpp]: Shouldn't these checks add `iarg`? If you have a 4 x 4 x 1 grid with the command:
`balance 0.9 x 0.1 0.1 0.1 y 0.1`
I think this check would miss the error.

Comment (akohlmey) [reply src/balance.cpp]: yup. well spotted. this appears to be a rather old bug that has survived a long time...

**Review by jtclemm — APPROVED** [review]
