### PR TITLE
Reaxc multi instance fix

### LINKED ISSUE #1432: [BUG] _Global variable in USER-REAXC can cause segfaults_
**Summary**

The LR variable defined in reaxc_lookup.cpp (line 32) is global and can cause problems if multiple pair_reaxc objects are created.

**Comments**

The LR variable should be made local to the pair_reaxc object or a new class should be defined that could contain the LR variable and have all of the reax functions as member variables.  This would involve a good deal of changes/additions/adjustments to the code, but I'm not thinking of a better approach.  Suggestions would be welcome.  I can likely implement a solution if we agree on the approach.

### PR DESCRIPTION
**Pull request by ellio167**
**Summary**

Implementation of reaxc fixes discussed in #1432 
closes #1432 

**Author(s)**

Ryan S. Elliott (U. Minnesota)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

no

**Post Submission Checklist**

_Please check the fields below as they are completed **after** the pull request has been submitted. Delete lines that don't apply_

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

### CODE REVIEW

**Comment by mkanski** [comment]
Hi, the changes needs to be done also for reax/c/omp, that's why some checks failed. The files are in src/USER-OMP.

File: src/USER-OMP/pair_reaxc_omp.h [hunk 1]
```diff
@@ -76,6 +76,7 @@ class PairReaxCOMP : public PairReaxC, public ThrOMP {
   }
 
  protected:
+  std::string fix_id;
```
Comment (akohlmey) [inline src/USER-OMP/pair_reaxc_omp.h]: @ellio167 we are currently trying to avoid having STL (and other) headers included in style file headers. Would you mind making fix_id a `const char *` and use sprintf() or strcat() to create the unique string, as it is done in other places?

Comment (ellio167) [reply src/USER-OMP/pair_reaxc_omp.h]: sure, I'll be happy to do that.
