### PR TITLE
Bugfix for fix pour and PBC

### LINKED ISSUE #1695: [BUG] fix pour: particles overlapping at z periodic boundary
Inserted particles across the z-periodic boundary can overlap with existing particles. Example code attached. From the dump file you will see that particles close to the z-boundary have very high stresses as they overlap on placement. From the dump file you will see that particles close to the z-boundary have very high stresses as they overlap on placement. 

7 Aug 2019 (and older versions)

**Expected Behavior**

fix_pour should check for overlaps between the particle being inserted, the other inserted particles and the pre-existing particles. It appears to do so, and this works for x and y, but not z 

**Steps to Reproduce**

Code attached with input file and input data and output data from running it. Compile lammps with Granular package. 

[fix_pour_bug.zip](https://github.com/lammps/lammps/files/3663920/fix_pour_bug.zip)

Please let me know if more info required thomas.shire@glasgow.ac.uk

### PR DESCRIPTION
**Pull request by rbberger**
**Summary**

There was a logic error in the `outside()` function used by fix pour.
The previous implementation was essentially doing this:

```
outside = outside_pbc_range || outside_regular_range
```

It should have been:

```
outside = outside_pbc_range && outside_regular_range
```

**Related Issues**

Closes #1695 

**Author(s)**

@rbberger 

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

insertions that were previously considered are now ignored if particles are in the PBC area

**Post Submission Checklist**

_Please check the fields below as they are completed **after** the pull request has been submitted. Delete lines that don't apply_

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

_Put any additional information here, attach relevant text or image files, and URLs to external sites (e.g. DOIs or webpages)_

### CODE REVIEW

File: src/GRANULAR/fix_pour.cpp [hunk 1]
```diff
@@ -782,25 +782,27 @@ int FixPour::overlap(int i)
...
     } else if (lo < boxlo) {
-      if (value > hi && value < lo + domain->prd[dim]) return 1;
+      // lower boundary crosses periodic boundary
+      outside_pbc_range = (value > hi && value < lo + domain->prd[dim]);
     } else if (hi > boxhi) {
-      if (value > hi - domain->prd[dim] && value < lo) return 1;
-    } else {
-      if (value < lo || value > hi) return 1;
+      // upper boundary crosses periodic boundary
+      outside_pbc_range = (value < lo && value > hi - domain->prd[dim]);
```
Comment (athomps) [inline src/GRANULAR/fix_pour.cpp]: This line still does not seem right to me. In this case, lo and hi are both inside the periodic cell, so the test should be:

 outside_pbc_range = (value < lo && value < hi );

The original version is correct too, since the two conditions are mutually exclusive.
