### PR TITLE
Collected small changes and fixes

### LINKED ISSUE #4797: file src/INTEL/TEST/mW.sw units inconsistency
The parameters in this file are mislabeled.
It cites Stillinger & Weber (1985), but the actual values correspond to the mW water model from:

Moore & Molinero, “Water Modeled as an Intermediate Element between Carbon and Silicon,” J. Phys. Chem. B 113, 4008 (2009).

Additionally, the parameters are expressed in real units, not metal units. For instance, ε = 6.189 is not in eV as stated, but in kcal/mol.

### PR DESCRIPTION
**Pull request by akohlmey**
**Summary**

This pull request combines multiple small changes and fixes.

**Related Issue(s)**

Fixes #4797 

**Author(s)**

Axel Kohlmeyer, Temple U

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Artificial Intelligence (AI) Tools Usage**

The GitHub Copilot coding instructions were mostly updated by GitHub Copilot.

**Backward Compatibility**

N/A

**Implementation Notes**

The following individual changes are included:
- remove references to https://ci.lammps.org and update information on automated testing
- update GitHub checkout action for testing workflows to version 6
- update GitHub coding instructions to follow best practices
- include LAMMPS version date only for 'release' and 'stable' branch when creating the manual. otherwise use 'Maintenance' (for 'maintenance 'branch) or 'Development' (for everything else)
- add deprecation messages for recently removed styles
- add more doxygen comments for LAMMPS class and Pointers class
- some more improvements for binary packaging on Linux
- remove some debug code
- reduce compiler warnings
- improve error messages and discussion of error details
- fix logic bug from last minute change in PR #4772
- update metadata in mW potential file in INTEL package tests

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system

### CODE REVIEW

File: src/lammps.cpp [hunk 1]
```diff
@@ -965,10 +996,13 @@ void LAMMPS::post_create()
   }
 }
 
-/* ----------------------------------------------------------------------
-   initialize top-level classes
-   do not initialize Timer class, other classes like Run() do that explicitly
-------------------------------------------------------------------------- */
+/** Initialize the LAMMPS top-level classes
```
Comment (stanmoore1) [inline src/lammps.cpp]: I think this type of comment style is harder to read and doesn't match the rest of LAMMPS.

File: src/pointers.h [hunk 2]
```diff
@@ -98,41 +100,40 @@ class Pointers {
...
-
-  MPI_Comm &world;
-  FILE *&infile;
-  FILE *&screen;
-  FILE *&logfile;
-
-  class AtomKokkos *&atomKK;
-  class MemoryKokkos *&memoryKK;
-  class Python *&python;
+  LAMMPS *lmp;            ///< LAMMPS instance
```
Comment (stanmoore1) [inline src/pointers.h]: I think `///<` is ugly.

File: src/lammps.cpp [hunk 3]
```diff
@@ -891,14 +913,23 @@ void LAMMPS::create()
...
-   check suffix consistency with installed packages
-   invoke package-specific default package commands
-     only invoke if suffix is set and enabled
-     also check if suffix2 is set
-   called from LAMMPS constructor and after clear() command
-     so that package-specific core classes have been instantiated
-------------------------------------------------------------------------- */
+/** Perform LAMMPS class tasks that require all base classes being set up
+ *
+\verbatim embed:rst
```
Comment (stanmoore1) [inline src/lammps.cpp]: Why are there `rst` commands in the comment? I think this makes the comment block harder to read.

**Review by stanmoore1 — COMMENTED** [review]
Most of the changes look good but I'm concerned that adding doxygen and rst commands into comment blocks makes them ugly, harder to read, and doesn't match the rest of LAMMPS.

File: src/lammps.cpp (hunk 1 above)
Comment (akohlmey) [reply src/lammps.cpp]: Show me a different way to transfer that kind of information into the manual without redundancies.  Some things take some getting used to, but the payoff in the long run is worth it.

We've transformed the C-language and Python-language interface so have only one documentation and set of comments so it is easier to keep it all consistent and up-to-date. The C++ programming interface is woefully missing; mostly because it is a lot of work. Since I found that GitHub Copilot is quite good at producing a usable draft for those comments, I am now working to have at least the generally usable members of the base classes documented.

File: src/pointers.h (hunk 2 above)
Comment (akohlmey) [reply src/pointers.h]: Please check out https://doxygen.nl/manual/docblocks.html#memberdoc for alternatives. Happy to apply a different one.

File: src/lammps.cpp (hunk 3 above)
Comment (akohlmey) [reply src/lammps.cpp]: This is the only way to insert references to other parts of the manual and write embedded documentation that is consistent with the rest of the manual.

While looking at the docs for the latest version of breathe, I've noticed an alternative tag where the asterisks can remain. Need to check how recent this is and if it works for all existing cases that we already have. https://breathe.readthedocs.io/en/latest/markups.html#handling-leading-asterisks

File: src/lammps.cpp (hunk 1 above)
Comment (stanmoore1) [reply src/lammps.cpp]: I think we need to get input from other developers on this, e.g. @athomps and/or @sjplimp.

Comment (akohlmey) [reply src/lammps.cpp]: > I think we need to get input from other developers on this, e.g. @athomps and/or @sjplimp.

I understand the desire to keep things the way they are, but we are already too far down the road of adding Doxygen comments to reverse this process. The benefits, especially in the long run, outweigh the discomfort, IMO.  Like with other "modernization" changes (even though Doxygen is hardly modern), it takes some time to get used to it, embrace it, and use it to the advantage of LAMMPS users and developers, especially future ones.  Happy to continue discussing this in private.

Comment (akohlmey) [reply src/lammps.cpp]: > I think we need to get input from other developers on this, e.g. @athomps and/or @sjplimp.

@stanmoore1 FYI, I've moved the doxygen related changes out of this pull request into #4793 to have them all in one place and not block merging this PR due to this discussion.

**Review by jtclemm — APPROVED** [review]

**Review by jtclemm — APPROVED** [review]

File: src/lammps.cpp (hunk 1 above)
Comment (stanmoore1) [reply src/lammps.cpp]: Thank you @akohlmey
