### PR TITLE
Removing calls to MPI_Abort from reax/c + a fix for a memory leak

### LINKED ISSUE #89: "clear" command doesn't free all memory with reax/c
From lammps-users:

Hello
I've encountered a problem with the "clear" command. It doesn't free memory when used along with pair_style reax/c and two 'run' commands in a loop.I'm attaching a simple input script which shows the problem. I'm using LAMMPS from 6 Nov 2015.
Cheers Michal 

```
label                   loopa
clear
units                   real
atom_style              charge
region                  universe block -10 10 -10 10 -10 10 units box
lattice                 sc 3
create_box              1 universe
mass                    1 12.09
create_atoms                1 box
pair_style              reax/c NULL checkqeq no
pair_coeff              * * ffield.reax.cho C
run                     0 
run                     0
jump                    SELF loopa
```

### PR DESCRIPTION
**Pull request by mkanski**
**Summary**

Current reax/c version in many situations invokes MPI_Abort. This is a problem when LAMMPS is called as library, since the error in Reax kill entire program. This PR removes all calls to MPI_Abort and replaces them with functions from the Error class. This is done also to warnings, which currently are printed directly to stderr. Additionally, this PR includes a fix for a memory leak described in #89. 

**Related Issues**

This PR fixes #89.

**Author(s)**

Michał Kański, Jagiellonian University

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Yes, it only changes internal reax/c functions

**Implementation Notes**

The calls to MPI_Abort and printfs to stderr are changed to functions from Error class. In order to do it, a pointer to LAMMPS object is passed to reax/c functions. It is quite invasive, but I haven't found a better method. There is still some work to be done, e.g. making the same changes to reax/c/omp, but before I do it, I'd like to ask for your opinion.

Memory leak

If there are multiple calls to `run` or `minimize` in a single LAMMPS simulation, there is a memory leak caused by the lines below. They zero allocation flags for reax/c lists, so they are allocated again without a deallocation first. The fix is to add a check if a list is already allocated. Probably the entire for can be deleted, although I have to check it. 

https://github.com/lammps/lammps/blob/c3acb3e4ef9272d042d31e51b3495acfce185244/src/USER-REAXC/pair_reaxc.cpp#L396-L397

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system

**Further Information, Files, and Links**

_Put any additional information here, attach relevant text or image files, and URLs to external sites (e.g. DOIs or webpages)_

### CODE REVIEW

**Comment by akohlmey** [comment]
@mkanski thanks for the efort, but i don't like the approach that you have taken here. Why don't you simply add a forward declaration like `LAMMPS_NS::Error *lmp_error` to one of the global structs that USER-REAXC uses (perhaps `global_parameters` from `reaxc_types.h`?), initialize it in the pair class constructor or wherever else needed and then grab it from there? Avoids having to change all reax specific function calls. At the very least, you would want to pass a pointer to Error, not the entire LAMMPS class.

**Comment by mkanski** [comment]
@akohlmey I agree it's not pretty. I've thought about adding the pointer to one of the Reax structures, but I hadn't found any which was used by all functions which can trigger an error, so I went with this approach, but I'll add the pointer to some of the structures to minimize the number of changes. Passing a pointer to Error instead of LAMMPS is a good point, I'll implement that as well.

**Comment by akohlmey** [comment]
> @akohlmey I agree it's not pretty. I've thought about adding the pointer to one of the Reax structures, but I hadn't found any which was used by all functions which can trigger an error, so I went with this approach, but I'll add the pointer to some of the structures to minimize the number of changes. Passing a pointer to Error instead of LAMMPS is a good point, I'll implement that as well.

the optimum is probably somewhere in the middle. i am not categorically against API changes, but those should be reduced to the minimum, e.g. passing a pointer to `Error` instead of passing `MPI_Comm` or similar.

> EDIT:
> I've noticed that one of the test failed, because KOKKOS version of Reax uses the same `sfree`, `smalloc`, `scalloc`, and some of the functions for tabulating long range interactions as reax/c. It's about 30 lines. May I change them as well?

yes. KOKKOS and USER-OMP 'reax/c' derived classes and functions should work consistently with the code in USER-REAXC.

File: src/USER-OMP/reaxc_forces_omp.cpp [hunk 1]
```diff
@@ -289,9 +289,10 @@ void Validate_ListsOMP( reax_system *system, storage * /*workspace */, reax_list
       else comp = bonds->num_intrs;
 
       if (End_Index(i, bonds) > comp) {
-        fprintf( stderr, "step%d-bondchk failed: i=%d end(i)=%d str(i+1)=%d\n",
-                 step, i, End_Index(i,bonds), comp );
-        MPI_Abort( comm, INSUFFICIENT_MEMORY );
+        char errmsg[256];
+        snprintf(errmsg, 256, "step%d-bondchk failed: i=%d end(i)=%d str(i+1)=%d\n",
+                  step, i, End_Index(i,bonds), comp );
+        system->error_ptr->all(FLERR,errmsg);
```
Comment (akohlmey) [inline src/USER-OMP/reaxc_forces_omp.cpp]: Are you sure this code triggers for all MPI ranks at the same time? otherwise, you have to use `error->one()`.

File: src/USER-OMP/reaxc_forces_omp.cpp [hunk 2]
```diff
@@ -315,9 +316,10 @@ void Validate_ListsOMP( reax_system *system, storage * /*workspace */, reax_list
         else comp = hbonds->num_intrs;
 
         if (End_Index(Hindex, hbonds) > comp) {
-          fprintf(stderr,"step%d-hbondchk failed: H=%d end(H)=%d str(H+1)=%d\n",
+          char errmsg[256];
+          snprintf(errmsg, 256, "step%d-hbondchk failed: H=%d end(H)=%d str(H+1)=%d\n",
                   step, Hindex, End_Index(Hindex,hbonds), comp );
-          MPI_Abort( comm, INSUFFICIENT_MEMORY );
+          system->error_ptr->all(FLERR, errmsg);
```
Comment (akohlmey) [inline src/USER-OMP/reaxc_forces_omp.cpp]: Same issue here. This looks more likely for calling `error->one()` instead of `error->all()`.

File: src/USER-REAXC/reaxc_ffield.cpp [hunk 3]
```diff
@@ -29,6 +29,9 @@
 #include "reaxc_ffield.h"
 #include "reaxc_tool_box.h"
 
+#include "lammps.h"
```
Comment (akohlmey) [inline src/USER-REAXC/reaxc_ffield.cpp]: it should be sufficient to include only "error.h" here.

File: src/USER-REAXC/reaxc_ffield.cpp [hunk 4]
```diff
@@ -158,15 +150,9 @@ char Read_Force_Field( FILE *fp, reax_interaction *reax,
     c = Tokenize( s, &tmp );
 
     /* Sanity checks */
-    if (c == 2 && !lgflag) {
```
Comment (akohlmey) [inline src/USER-REAXC/reaxc_ffield.cpp]: why delete this here? to provide this specific error message and not some generic "inconsistent ffield file" this check has to come first.

File: src/USER-REAXC/reaxc_forces.cpp [hunk 5]
```diff
@@ -161,9 +163,10 @@ void Validate_Lists( reax_system *system, storage * /*workspace*/, reax_list **l
         else comp = hbonds->num_intrs;
 
         if (End_Index(Hindex, hbonds) > comp) {
-          fprintf(stderr,"step%d-hbondchk failed: H=%d end(H)=%d str(H+1)=%d\n",
+          char errmsg[256];
+          snprintf(errmsg, 256, "step%d-hbondchk failed: H=%d end(H)=%d str(H+1)=%d\n",
                   step, Hindex, End_Index(Hindex,hbonds), comp );
-          MPI_Abort( comm, INSUFFICIENT_MEMORY );
+          system->error_ptr->all(FLERR, errmsg);
```
Comment (akohlmey) [inline src/USER-REAXC/reaxc_forces.cpp]: same as in USER-OMP: does this error really get always triggered by all MPI ranks?

File: src/USER-REAXC/reaxc_types.h [hunk 6]
```diff
@@ -39,6 +39,10 @@
 #include <sys/time.h>
 #include "accelerator_kokkos.h"
 
+#include "lammps.h"
```
Comment (akohlmey) [inline src/USER-REAXC/reaxc_types.h]: this is not good. you should not add includes to LAMMPS headers to reax/c headers. we only need a forward declaration here. so something like the following forward declaration should do:
```
namespace LAMMPS_NS { class Error; }
```
...and then you can use `LAMMPS_NS::Error *` and use the `error.h` include only in the .cpp file(s).

File: src/USER-REAXC/reaxc_types.h [hunk 7]
```diff
@@ -39,6 +39,10 @@
...
+#include "error.h"
+using LAMMPS_NS::Error;
```
Comment (akohlmey) [inline src/USER-REAXC/reaxc_types.h]: we particularly do not want `using` anywhere in a header file.

Comment (mkanski) [reply src/USER-REAXC/reaxc_types.h]: I removed my change, but there is another `using` here: https://github.com/lammps/lammps/blob/eedc88eb9b82701740e48903634395e7990b2cf3/src/USER-REAXC/reaxc_types.h#L399

File: src/USER-REAXC/reaxc_ffield.cpp (hunk 4 above)
Comment (mkanski) [reply src/USER-REAXC/reaxc_ffield.cpp]: I actually moved it below (around lines 314-318), because this check wasn't triggered with my test potential with only one element, but this was a mistake - both checks are necessary. I'll restore it.

**Comment by mkanski** [comment]
I've included your remarks. I will test the rest of `error->all` for possible MPI deadlocks later this week.

I have a question - `smalloc()` and `scalloc()` functions can return NULL, if there's no enough space (or for some reason the requested size is negative), but I believe this is almost always lethal. There are no checks if the returned pointer is NULL, so LAMMPS crashes with a segmentation fault. Shouldn't these warnings be changed to errors?

File: src/USER-REAXC/reaxc_types.h (hunk 7 above)
Comment (akohlmey) [reply src/USER-REAXC/reaxc_types.h]: need to check about getting rid of that, too. the code in USER-REAXC has been rather "dirty" when it was merged into LAMMPS and caused trouble because of that multiple times. So this is a work-in-progress and every opportunity to clean it up incrementally is welcome. i will sort this one out.

**Comment by akohlmey** [comment]
> I've included your remarks. I will test the rest of `error->all` for possible MPI deadlocks later this week.
> 
> I have a question - `smalloc()` and `scalloc()` functions can return NULL, if there's no enough space (or for some reason the requested size is negative), but I believe this is almost always lethal. There are no checks if the returned pointer is NULL, so LAMMPS crashes with a segmentation fault. Shouldn't these warnings be changed to errors?

i agree. the equivalent functions in memory.cpp are errors, too. so please do it.

File: src/USER-REAXC/reaxc_types.h (hunk 7 above)
Comment (akohlmey) [reply src/USER-REAXC/reaxc_types.h]: the required change is now in PR #1402 as commit 6cb120d691b656e32a5619005041768842683d6b

**Comment by mkanski** [comment]
I believe this PR is completed. I checked all calls to error->all and there should be no MPI deadlocks.
The reason of CMAKE build failing doesn't seem to be connected to my changes. The error is "Could NOT find TBB (missing: TBB_LIBRARY TBB_INCLUDE_DIR)"

**Comment by akohlmey** [comment]
@mkanski FYI, to "repair" the failing `cmake-serial-pr` test, you will need to merge the current master into your branch. We just fixed a few issues and updated some files, which will break backward compatibility.

**Comment by mkanski** [comment]
It should work now.

File: src/USER-OMP/pair_reaxc_omp.cpp [hunk 8]
```diff
@@ -113,7 +113,7 @@ PairReaxCOMP::~PairReaxCOMP()
   if (setup_flag) {
     reax_list * bonds = lists+BONDS;
     for (int i=0; i<bonds->num_intrs; ++i)
-      sfree(bonds->select.bond_list[i].bo_data.CdboReduction, "CdboReduction");
+      sfree(LAMMPS_NS::Pointers::lmp->error, bonds->select.bond_list[i].bo_data.CdboReduction, "CdboReduction");
```
Comment (akohlmey) [inline src/USER-OMP/pair_reaxc_omp.cpp]: shouldn't you have access to `error` directly, since `PairReaxCOMP` derives from `PairReaxC` which derives from `Pointers`?

Comment (mkanski) [reply src/USER-OMP/pair_reaxc_omp.cpp]: Yes, you are right. I started with lmp->error which gave me an ambiguous reference error during compilation and this was the first workaround I found.

File: src/USER-REAXC/pair_reaxc.cpp [hunk 9]
```diff
@@ -108,6 +109,8 @@ PairReaxC::PairReaxC(LAMMPS *lmp) : Pair(lmp)
   system->bndry_cuts.ghost_cutoff = 0;
   system->my_atoms = NULL;
   system->pair_ptr = this;
+  system->error_ptr = this->lmp->error;
```
Comment (akohlmey) [inline src/USER-REAXC/pair_reaxc.cpp]: this could be two more simplifications: replace `this->lmp->error` with `error`

File: src/USER-REAXC/pair_reaxc.cpp [hunk 10]
```diff
@@ -436,13 +440,14 @@ void PairReaxC::setup( )
...
+    PreAllocate_Space( system, control, workspace );
     write_reax_atoms();
 
     int num_nbrs = estimate_reax_lists();
     if(!Make_List(system->total_cap, num_nbrs, TYP_FAR_NEIGHBOR,
-                  lists+FAR_NBRS, world))
-      error->all(FLERR,"Pair reax/c problem in far neighbor list");
+                  lists+FAR_NBRS))
+      error->one(FLERR,"Pair reax/c problem in far neighbor list");
+    (lists+FAR_NBRS)->error_ptr=lmp->error;
```
Comment (akohlmey) [inline src/USER-REAXC/pair_reaxc.cpp]: and an `lmp->error` that could be `error`.

File: src/USER-REAXC/reaxc_allocate.cpp [hunk 11]
```diff
@@ -86,39 +88,39 @@ void DeAllocate_System( reax_system *system )
   int ntypes;
   reax_interaction *ff_params;
 
-  // dealloocate the atom list
-  sfree( system->my_atoms, "system->my_atoms" );
+  // deallocate the atom list
```
Comment (akohlmey) [inline src/USER-REAXC/reaxc_allocate.cpp]: fixing speelink errors in comments. love it!!

**Comment by akohlmey** [comment]
@sjplimp @mkanski it is great to see, that people care about cleaning up code. looks like our next stable release is going to be the best and most stable ever. :+1: :+1:

**Comment by mkanski** [comment]
@akohlmey I'm glad I could help. :) Thank you for your remarks, this PR would look like much worse without them.
