### PR TITLE
Fix memory leaks and invalid memory access in USER-BOCS

### LINKED ISSUE #1109: Plug memory leaks in fix bocs
## Summary

Fix bocs does malloc()/calloc() small chunks of memory all over the place but doesn't seem to free() them.

## Type of Issue

Bug report

## Detailed Description (Enhancement Suggestion)

The code should use either stack allocations or call free() on 

## LAMMPS Version (Bug Report)

Observed with version 5 Sep 2018, but has been in the code since the package was added.

## Expected Behavior (Bug Report)

No memory leak.

### PR DESCRIPTION
**Pull request by eagunn**
This is a work-in-progress PR needing at least some small amounts of feedback from core developers on some of the code modernization changes. (I’ll add my specific questions as comments below.)

**Summary**

Corrected two issues in code identified by valgrind: 1) memory leaks (the subject of the original #1109) and 2) an invalid memory access (reading from beyond the end of an array).

Replaced many dynamically-allocated (calloc and free) local arrays with std::vector. Also, reorganized include statements per new conventions and updated messages to use strings and fmt.

No changes in analysis results are expected or intended. This is pure refactoring except for a bit of error message cleanup.

**Related Issues**

Closes #1109.
Attempts to follow new coding conventions for include statement order and message formatting (#2102).

**Author(s)**

E. Anne Gunn, Sheridan College (NWCCD)
agunn@sherprog.com

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Analysis results should be unchanged for all input files. Some output files contain a bit more information, but that would only affect backward compatibility if you are using an automated diff tool to compare old to new.

**Implementation Notes**
Valgrind was used to identify the memory leaks and invalid memory access and to verify fixes were working.

For testing, I used an existing methanol data set from the examples tree and a sample cgheptane data set supplied by original author @mdelyser. I then made several variations of the cgheptane input files to invoke the three different types of analysis (analytical, linear spline, and cubic spline) and also as many of the file-input error messages as possible. Output files for each input set were generated using the lammps/master branch and then diffed with progressive new generations as I made changes. The complete file set for this verification process is being checked into the examples tree with this PR.

@mdelyser has since verified the code against a different set of input file. "The three simulations I ran (analytic, linear, cubic) all behaved the same (within error), and they ran fine distributed across 24 cores using MPI."

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

NA

### CODE REVIEW

**Comment by eagunn** [comment]
@akohlmey Please take a look at src/USER-BOCS/fix_bocs.cpp and give me feedback on the include list.

- The recommended order is to have "LAMMPS local headers (preferably in alphabetical order)". But your recent practice puts fmt/format.h consistently at the end of that list. Is fmt/format.h a known exception to the order, as mpi.h is? 
- Do you object to the white space line between the different types of includes?

File: src/USER-BOCS/fix_bocs.h [hunk 1]
```diff
@@ -151,7 +151,8 @@ class FixBocs : public Fix {
   void nhc_press_integrate();
 
   int read_F_table(char *, int);
-  void build_cubic_splines(double **);
+  int build_linear_splines(std::vector<std::vector<double>>);
```
Comment (akohlmey) [inline src/USER-BOCS/fix_bocs.h:154]: This API change is not good. Unless is is a (small) temporary array, multi-dimensional data should be allocated with `memory->create()` and deleted with `memory->destroy()`. But this is even worse since C++ does call by value and thus you create a needless copy and cannot pass it back. If the data is not used elsewhere, it should not be passed as an argument, but allocated locally, if it is needed elsewhere, it cannot be passed by value.

**Comment by akohlmey** [comment]
> @akohlmey Please take a look at src/USER-BOCS/fix_bocs.cpp and give me feedback on the include list.
> 
> * The recommended order is to have "LAMMPS local headers (preferably in alphabetical order)". But your recent practice puts fmt/format.h consistently at the end of that list. Is fmt/format.h a known exception to the order, as mpi.h is?

this is not a strict rule. fmt/format.h is special since its feature has been included in C++20 so it will at some point become a system header. also the include file policy may need to be reviewed. already certain includes are used in lmptype.h which is used almost everywhere. so I expect in the future, that certain includes, like <cstdio>, <string>, "fmt/format.h", "utils.h", can be safely assumed to be available because they will be included in a file that is a prerequisite for almost all LAMMPS code. Then the individual includes can be removed.

furthermore, i expect that at some point we will have a clang-format rule file that will describe the source code format we agree on.

> * Do you object to the white space line between the different types of includes?

no.

**Comment by akohlmey** [comment]
@eagunn all folders and custom scripts that are labeled as "test" should not be part of this feature branch and not included in the pull request.

File: src/USER-BOCS/fix_bocs.h (hunk 1 above)
Comment (eagunn) [reply src/USER-BOCS/fix_bocs.h]: Good catch on the function parameter. Thank you.  I've been spending so much time in the languages that pass arrays and objects by reference automatically that I let my guard down. But the pass-by-value problem is easily fixed by making the parameter a const reference to the vector. The vector is quite local; it exists only during the course of reading and processing an input data file. The data structure passed to the compute module is still a `double **`.

Checking for understanding here: Do you have a more general concern about the ability of vectors to handle reasonably large multidimensional arrays of doubles? The coder overhead is high to correctly manage the calloc/free code that was being used in this code before. A switch to vectors decreases that burden without having to change any of the code that accesses the actual array elements. Now that we have C++11 at our command, are there good reasons not to use vectors consistently for local data structures?

Comment (eagunn) [reply src/USER-BOCS/fix_bocs.h]: I've submitted a change to the build_xxx_splines signatures to switch to passing a const reference to the vector.

**Comment by eagunn** [comment]
I'm trying to understand your objection here.
> @eagunn all folders and custom scripts that are labeled as "test" should not be part of this feature branch and not included in the pull request.

Is this a problem with how I've named/organized my examples? Or more fundamentally with the example sets I'm trying to preserve?

I've checked through the examples tree a bit. It seems to me to be full of grouped sets of input(lammps)/data/output files with a large variety in the folder and file naming conventions used. And there are already a few custom scripts for running groups of examples, as well. So I'm not understanding what is different about these new bocs file sets unless its that I used the folder name "test" to distinguish files that are primarily examples of how the code works and not examples of science one can do with the code.

I'd be happy to reorganize / rename these if that would help. But I spent a reasonable amount of time creating a set of files to cover the code I was changing. I'd like to think that most/all of the inputs could become the basis for unit tests someday. I would prefer not to risk losing them by having them stranded in an off-branch of my private repo.

**Comment by akohlmey** [comment]
> I'm trying to understand your objection here.
> 
> > @eagunn all folders and custom scripts that are labeled as "test" should not be part of this feature branch and not included in the pull request.
> 
> Is this a problem with how I've named/organized my examples? Or more fundamentally with the example sets I'm trying to preserve?
> 
> I've checked through the examples tree a bit. It seems to me to be full of grouped sets of input(lammps)/data/output files with a large variety in the folder and file naming conventions used. And there are already a few custom scripts for running groups of examples, as well. So I'm not understanding what is different about these new bocs file sets unless it's that I used the folder name "test" to distinguish files that are primarily examples of how the code works and not examples of science one can do with the code.

custom scripts are the exception. they are usually only tolerated to run post-processing. some are there for historic reasons, as we are now more thorough in checking what gets added than in the past. 
the fact that inputs are meant to be used for testing functionality instead of demonstrating the use is the point. tests for checking the correct function of features in LAMMPS can be added to the lammps-testing repo or in the unittest tree, but then in a more low level testing using the googletest framework.
in part those additions looks like they are only for your convenience (e.g. the cmake script in the package subdirectory) or they have paths that can only work for you. those should be removed entirely.

> I'd be happy to reorganize / rename these if that would help. But I spent a reasonable amount of time creating a set of files to cover the code I was changing. I'd like to think that most/all of the inputs could become the basis for unit tests someday. I would prefer not to risk losing them by having them stranded in an off-branch of my private repo.

I appreciate your concern, and if this was a mainstream feature, I might share it. Under the current circumstances, avoiding additional clutter in the repo is of higher priority than losing some tests. The best is probably to you keep them locally and try to convert the core of it to either a unittest entry (we don't have a template for testing fixes yet, though) or integrate them into the regression testing tree in the lammps-testing repo.

File: src/USER-BOCS/fix_bocs.cpp [hunk 2]
```diff
@@ -630,154 +640,202 @@ void FixBocs::init()
...
-    while( fgets(line,199,fpi)) {
-      ++n_entries;
-      test_sscanf = sscanf(line," %f , %f ",&f1, &f2);
+    int lineNum = 0;  // this value is only for  message
+    int numBadVolumeIntervals = 0; // count these for message
+    float f1, f2;
+    int test_sscanf;
+    for (int i = 0; i < inputLines.size(); ++i) {
+      lineNum++;  // count each line processed now so lineNum messages can be 1-based
+      test_sscanf = sscanf(inputLines.at(i).c_str()," %f , %f ",&f1, &f2);
```
Comment (akohlmey) [inline src/USER-BOCS/fix_bocs.cpp:700]: This should be using the ValueTokenizer class.

File: src/USER-BOCS/fix_bocs.cpp [hunk 3]
```diff
@@ -630,154 +640,202 @@ void FixBocs::init()
...
-    char errmsg[MAX_MESSAGE_LENGTH];
-    snprintf(errmsg,MAX_MESSAGE_LENGTH,
-             "Bad volume / pressure-correction data: %s\nSee details above",filename);
-    error->all(FLERR,errmsg);
+    std::string errmsg = fmt::format("Bad volume / pressure-correction data: {}\nSee details above", filename);
+    error->message(FLERR,errmsg.c_str());
   }
 
-  if (p_basis_type == 1)
+  if (p_basis_type == BASIS_LINEAR_SPLINE)
```
Comment (akohlmey) [inline src/USER-BOCS/fix_bocs.cpp:761]: When refactoring the code, you may also consider updating the source formatting. We prefer
```
if (condition) {
    ...
} else {
   ...
}
```
and equivalent for loops

File: src/USER-BOCS/fix_bocs.h (hunk 1 above)
Comment (akohlmey) [reply src/USER-BOCS/fix_bocs.h]: > Checking for understanding here: Do you have a more general concern about the ability of vectors to handle reasonably large multidimensional arrays of doubles? The coder overhead is high to correctly manage the calloc/free code that was being used in this code before. A switch to vectors decreases that burden without having to change any of the code that accesses the actual array elements. Now that we have C++11 at our command, are there good reasons not to use vectors consistently for local data structures?

the problem of the previous code is that it didn't use the memory class, which can allocate and delete multi-dimensional arrays in one go *and* nullify the pointer after deleting. That made it look clumsy. Also, the memory class has provisions for allocating memory with a preferred alignment and is integrated into the error reporting when malloc fails. When using C++ features you would also have to wrap everything into try/catch blocks to cleanly handle memory allocation issues and shut down parallel runs cleanly. My take on using containers is: we use them only when we can take advantage of their additional features, e.g. use iterators, or the size() member function (in case the size is unknown) or want to add/remove elements incrementally. What to use also depends on the specific use case. You can see that in the use of the tokenizer class (for speed) or the utils::split_words() function (for consistency and convenience).

Comment (eagunn) [reply src/USER-BOCS/fix_bocs.h]: Crikey. @akohlmey, I think I'm finally understanding your first comment above from 4 Aug. Sorry to seem dense. The USER/fix_bocs code is the only code within LAMMPS I've ever worked on. I simply took it on its own terms and tried to fix specific problems from there. It contained no use of the Memory class, only raw calloc and free calls. 

Not taking anything for granted here, would you please confirm the accepted best practice for replacing calloc, which both allocates memory and initializes all bits to 0 (where the intent was probably to initialize all entries in the array to 0.0).

If the old code was:
`double *z = (double *)calloc(n, sizeof(double));`
...
`free(z);`

The LAMMPS best practice code would be:
`double *z;`
`memory->create(z, n, "z");`
`for (int i = 0; i < n; i++) { z[i] = 0.0; }`
...
`memory->destroy(z);`

File: src/USER-BOCS/fix_bocs.cpp (hunk 3 above)
Comment (eagunn) [reply src/USER-BOCS/fix_bocs.cpp:761]: I also prefer the opening brace on the same line as the condition. I will be happy to reformat once we get through the other code review items. I did not want to make your task of diffing my changes more complicated. I'm taking enough of your time with this one small change as it is.

File: src/USER-BOCS/fix_bocs.cpp [hunk 4]
```diff
@@ -630,154 +640,202 @@ void FixBocs::init()
...
 {
-  FILE *fpi;
-  int N_columns = 2, n_entries = 0, i;
-  float f1, f2;
-  int test_sscanf;
-  double **data = (double **) calloc(N_columns,sizeof(double *));
-  char * line = (char *) calloc(200,sizeof(char));
+  DblVector volumeVec;
+  DblVector pressureVec;
+  std::vector<DblVector> data;
```
[the remark this answers is not in the document]
Comment (eagunn) [reply src/USER-BOCS/fix_bocs.cpp:645]: Understood. Please see my reply above.

File: src/USER-BOCS/fix_bocs.cpp [hunk 5]
```diff
@@ -630,154 +640,202 @@ void FixBocs::init()
...
+  FILE *fpi = fopen(filename,"r");
+  if (fpi) {
+    // Old code read the input file twice. Now we simply
+    // read all the lines from the input file into a string vector,
+    // then work with the data in-memory rather than do a second pass
+    // through the file.
+    // NB: LAMMPS coding guidelines prefer cstdio so we are intentionally
+    // foregoing  reading with getline
+    std::string message = fmt::format("INFO: About to read data file: {}", filename);
+    error->message(FLERR, message.c_str());
```
[the remark this answers is not in the document]
Comment (eagunn) [reply src/USER-BOCS/fix_bocs.cpp:658]: Ack. I'll simplify those calls. I knew that was the direction for message() but didn't know you had gotten there. Thanks.

File: src/USER-BOCS/fix_bocs.cpp [hunk 6]
```diff
@@ -630,154 +640,202 @@ void FixBocs::init()
...
   bool badInput = false;
-  char badDataMsg[MAX_MESSAGE_LENGTH];
-  fpi = fopen(filename,"r");
-  if (fpi)
-  {
-    while (fgets(line,199,fpi)) { ++n_entries; }
-
-    for (i = 0; i < N_columns; ++i)
-    {
-      data[i] = (double *) calloc(n_entries,sizeof(double));
```
[the remark this answers is not in the document]
Comment (eagunn) [reply src/USER-BOCS/fix_bocs.cpp:649]: Understood. See reply above.

File: src/USER-BOCS/fix_bocs.cpp (hunk 2 above)
Comment (eagunn) [reply src/USER-BOCS/fix_bocs.cpp:700]: Cool. I'll figure that out.

File: src/USER-BOCS/fix_bocs.h (hunk 1 above)
Comment (akohlmey) [reply src/USER-BOCS/fix_bocs.h]: @eagunn yes, that works. But I don't think that the clearing of the array is needed. Also the whole file reading code looks needlessly convoluted and complex. Like it was taken from some other application. On top of that you need to keep in mind, that many people that contribute to scientific software have no formal training in programming and sometimes get stuck in an "expert beginner" state, where their programming is full of quirks that are typical for beginners, but have become experienced enough in their ways to more-or-less achieve their objectives. When looking at the example folder, this looks like the clearing of the allocated storage is not needed, since the array is dimensioned for the data to be read.
I would suggest to look at pair style table as a template for how to read such tables.

You should also need to keep in mind, that you are looking at a "user" package and particularly one that was added at a time, when the barrier for adding code was deliberately kept very low. This code would not be merged like this anymore. We now work with people to improve their code to meet higher minimum standards, as we have found out that this is more effective that to merge it first and then try to rectify style issues later. This also reflects that change that I am not handling the first contact with contributors, while in the past I would often only see new contributions after they were already added and could give my suggestions and comments only later on (which then frequently resulted in me doing the touching up of the code). So we have more conventional protocols now (even though I - as well - have no formal training, but had lots of guidance from people who had and also have now 25+ years of working on maintaining scientific software. so if there is a mistake to be made, I have made it myself and thus can more easily spot it when other untrained people do them.).

Comment (eagunn) [reply src/USER-BOCS/fix_bocs.h]: I've converted all dynamically allocated arrays/matrices of doubles to use LAMMPS-standard memory class.

File: src/USER-BOCS/fix_bocs.cpp (hunk 2 above)
Comment (eagunn) [reply src/USER-BOCS/fix_bocs.cpp:685]: @akohlmey Would you be open to my resolving all the other issues you've raised with this PR but deferring the conversion of the file-reading code to another pass? I'm more than happy to do that work but would like to get the fixed for the lost memory and invalid read merged and put to bed. My teaching semester approaches rapidly and I don't want the fixes for the lost memory to get stranded in my repo if it takes me a while to get to tthe file-reading changes.

File: src/USER-BOCS/fix_bocs.cpp (hunk 3 above)
Comment (eagunn) [reply src/USER-BOCS/fix_bocs.cpp:746]: I believe I've addressed all of the concerns you've raised so far except the file-reading modernization. See my request above. I'll work on the reformatting locally but not push those changes till you've had a chance to review my fixes-so-far.

File: src/USER-BOCS/testData/user-bocs.cmake [hunk 7]
```diff
@@ -0,0 +1,8 @@
+# preset that turns on just a few, frequently used packages
```
Comment (akohlmey) [inline src/USER-BOCS/testData/user-bocs.cmake:1]: Please remove this file, too.

File: src/USER-BOCS/fix_bocs.cpp [hunk 8]
```diff
@@ -200,19 +207,18 @@ FixBocs::FixBocs(LAMMPS *lmp, int narg, char **arg) :
...
                                "Supply a file name after cubic_spline.");
-        p_basis_type = 2;
+        p_basis_type = BASIS_CUBIC_SPLINE;
         spline_length = read_F_table( arg[iarg+1], p_basis_type );
         iarg += 2;
       }  else {
-        char errmsg[256];
-        snprintf(errmsg,256,"CG basis type %s is not recognized\nSupported "
-                 "basis types: analytic linear_spline cubic_spline",arg[iarg]);
+        std::string errmsg = fmt::format("CG basis type {} is not recognized\nSupported "
```
Comment (akohlmey) [inline src/USER-BOCS/fix_bocs.cpp:220]: This kind of statement doesn't really need a temporary std::string type instance. you can put the call to fmt::format() right  as an argument to error->all().

File: src/USER-BOCS/compute_pressure_bocs.cpp [hunk 9]
```diff
@@ -212,13 +221,13 @@ double ComputePressureBocs::find_index(double * grid, double value)
 
   if (value >= grid[i] && value <= (grid[i] + spacing)) { return i; }
 
+  char errmsg[256];
+  snprintf(errmsg,256,"find_index could not find value in grid for value: %f",value);
+  error->all(FLERR,errmsg);
```
Comment (akohlmey) [inline src/USER-BOCS/compute_pressure_bocs.cpp:226]: This could use fmt::format() just as the fix does.

File: src/USER-BOCS/compute_pressure_bocs.cpp [hunk 10]
```diff
@@ -122,6 +127,10 @@ ComputePressureBocs::~ComputePressureBocs()
   delete [] vector;
   delete [] vptr;
   if (phi_coeff) free(phi_coeff);
+
+  // Any splines data that was sent in from fix_bocs must be
+  // freed here, after it has been used.
+  memory->destroy(splines);
```
Comment (akohlmey) [inline src/USER-BOCS/compute_pressure_bocs.cpp:133]: This is very unusual and not a good idea. We need to correct this eventually. If the fix allocates the storage, it should free it. We have an established mechanism to share access with the "extract" function. The compute can use "extract" to retrieve pointers from the fix.

Comment (akohlmey) [reply src/USER-BOCS/compute_pressure_bocs.cpp:133]: Since the fix creates the compute, it can delete the splines data after the compute is deleted in the fix destructor.

File: src/USER-BOCS/fix_bocs.cpp [hunk 11]
```diff
@@ -807,21 +856,35 @@ void FixBocs::build_cubic_splines( double **data )
...
+  memory->destroy(d);
+
+  memory->destroy(h);
+  memory->destroy(alpha);
+  memory->destroy(l);
+  memory->destroy(mu);
+  memory->destroy(z);
+
+  message = fmt::format("INFO: leaving build_cubic_splines, numSplines = {}", numSplines);
+  error->message(FLERR, message);
```
Comment (akohlmey) [inline src/USER-BOCS/fix_bocs.cpp:884]: informational messages should only be printed on MPI ranks where `comm->me == 0`. Otherwise there are N lines of output when running in parallel with N MPI processes.

File: src/USER-BOCS/fix_bocs.cpp [hunk 12]
```diff
@@ -807,21 +856,35 @@ void FixBocs::build_cubic_splines( double **data )
...
+  int numSplines = 0;
+  for (int idx = 0; idx < n - 1; ++idx)
   {
+    splines[0][idx] = data[0][idx];
     splines[1][idx] = a[idx];
     splines[2][idx] = b[idx];
     splines[3][idx] = c[idx];
     splines[4][idx] = d[idx];
-    splines[0][idx] = data[0][idx];
+    numSplines++;
```
Comment (akohlmey) [inline src/USER-BOCS/fix_bocs.cpp:869]: why count here? numSplines would be n-1.

File: src/USER-BOCS/fix_bocs.cpp [hunk 13]
```diff
@@ -630,154 +635,194 @@ void FixBocs::init()
...
+          //message = fmt::format("INFO: current volume interval: {}", currVolumeInterval);
+          //error->message(FLERR,message);
           if (fabs(currVolumeInterval - stdVolumeInterval) > volumeIntervalTolerance) {
-            snprintf(badDataMsg,MAX_MESSAGE_LENGTH,
-                     "BAD VOLUME INTERVAL: spline analysis requires uniform"
-                     " volume distribution, found inconsistent volume"
-                     " differential, line %d of file %s\n\tline: %s",
-                     n_entries,filename,line);
-            error->message(FLERR,badDataMsg);
+            message = fmt::format("ERROR: Bad volume interval. Spline analysis requires uniform"
```
Comment (akohlmey) [inline src/USER-BOCS/fix_bocs.cpp:706]: Since all MPI ranks seem to be reading the file, this message should only be printed on rank 0. Or the reader should be only run on MPI rank 0 and then the data needs to be sent to the other MPI ranks with MPI_Bcast().

File: src/USER-BOCS/fix_bocs.cpp [hunk 14]
```diff
@@ -630,154 +635,194 @@ void FixBocs::init()
...
       }
+      if (badInput)
+      {
+        numBadVolumeIntervals++;
+      }
+    }
+
+    if (numBadVolumeIntervals) {
+      message = fmt::format("INFO: total number bad volume intervals = {}", numBadVolumeIntervals);
+      error->message(FLERR,message);
```
Comment (akohlmey) [inline src/USER-BOCS/fix_bocs.cpp:733]: please see my other comments about messages printed to the screen. In this case, actually removing the "INFO" tag and using message->warning() would be more appropriate.

File: src/USER-BOCS/fix_bocs.cpp (hunk 3 above)
Comment (akohlmey) [reply src/USER-BOCS/fix_bocs.cpp:746]: Had another look and found some more stuff that is not quite the way it is commonly done in LAMMPS.

File: src/USER-BOCS/fix_bocs.cpp (hunk 2 above)
Comment (akohlmey) [reply src/USER-BOCS/fix_bocs.cpp:685]: Yes, the refactoring of the file reading can wait.

File: src/USER-BOCS/compute_pressure_bocs.cpp (hunk 10 above)
Comment (eagunn) [reply src/USER-BOCS/compute_pressure_bocs.cpp:133]: @akohlmey , I'd prefer to figure this out and get it right now since this is the core of the memory leak fix. 

I will try moving the delete to the fix destructor. At some point I had convinced myself that the data object might need  to outlive the fix object. But @mdelyser has a multi-threaded environment for testing. So, after I make the change to move the delete to the fix destructor, I will ask him to re-test.

If that simple change does not work safely, I will investigate the extract mechanism.

File: src/USER-BOCS/testData/user-bocs.cmake (hunk 7 above)
Comment (eagunn) [reply src/USER-BOCS/testData/user-bocs.cmake:1]: Absolutely. Should never have made it into the repo.

File: src/USER-BOCS/fix_bocs.cpp (hunk 3 above)
Comment (eagunn) [reply src/USER-BOCS/fix_bocs.cpp:746]: Will work through the new comments and push fixes. May not be today due to teaching commitments but I'll get'em done.

File: src/USER-BOCS/testData/user-bocs.cmake (hunk 7 above)
Comment (eagunn) [reply src/USER-BOCS/testData/user-bocs.cmake]: Folder and file both removed.

File: src/USER-BOCS/compute_pressure_bocs.cpp (hunk 10 above)
Comment (eagunn) [reply src/USER-BOCS/compute_pressure_bocs.cpp]: Code has been moved to fix destructor and tested by me locally. I've committed and will request author @mdelyser test in his multithreaded environment.

**Comment by akohlmey** [comment]
@eagunn updated your branch to current master so it includes updates for a problem that made the compilation tests fail. Please let me know when you feel I should take another (final?) look at this to get it merged.

**Comment by eagunn** [comment]
> @eagunn updated your branch to current master so it includes updates for a problem that made the compilation tests fail. Please let me know when you feel I should take another (final?) look at this to get it merged.

Thank you. Original author is testing in a multi-threaded environment. If test is successful, I'll make a pass over messages, per your suggestions, then reformat the code. Sure hoping to have a final for you to look at no later than early next week.

File: src/USER-BOCS/fix_bocs.cpp (hunk 11 above)
Comment (eagunn) [reply src/USER-BOCS/fix_bocs.cpp]: Done.

File: src/USER-BOCS/fix_bocs.cpp (hunk 12 above)
Comment (eagunn) [reply src/USER-BOCS/fix_bocs.cpp]: Count was vestigial, intended to be a sort of a breadcrumb for original authors to orient themselves as they compared old/new code. But you're absolutely right; computationally it makes no sense. Code simplified now.

File: src/USER-BOCS/compute_pressure_bocs.cpp (hunk 10 above)
Comment (eagunn) [reply src/USER-BOCS/compute_pressure_bocs.cpp]: Original author has tested in his clustered environment and verified new destructor-based destroy works.

File: src/USER-BOCS/fix_bocs.cpp (hunk 8 above)
Comment (eagunn) [reply src/USER-BOCS/fix_bocs.cpp:222]: I made another pass through and moved most messages formatting directly into the call to the error method.
I kept formatting to a temp string in a couple of cases where the formatted output was long/complex and, IMO, an embedded call would be hard to read.

File: src/USER-BOCS/fix_bocs.cpp (hunk 3 above)
Comment (eagunn) [reply src/USER-BOCS/fix_bocs.cpp]: .cpp files reformatted using a .clang-format file derived from your unit-test one.
I changed the spacing back to 2 from the unit-test 4.

**Comment by eagunn** [comment]
@akohlmey I believe this PR is, at last, ready to move out of WIP status. 
Do you want me to create a new branch with all my recent fixes squashed into a single commit and base a new PR off that branch?
Or can I simply push the Ready for review button on this one?

File: src/USER-BOCS/fix_bocs.cpp (hunk 3 above)
Comment (akohlmey) [reply src/USER-BOCS/fix_bocs.cpp]: > .cpp files reformatted using a .clang-format file derived from your unit-test one.
> I changed the spacing back to 2 from the unit-test 4.

Sorry, but that reformat was a mistake. The clang-format is a test and only approved by @rbberger and me. It does several things different from the preferences of @sjplimp and that is why we are not applying it globally, but only for the unittest branch. Could you try to undo it? or else I would likely have to manually reformat it. :-(

**Comment by akohlmey** [comment]
> @akohlmey I believe this PR is, at last, ready to move out of WIP status.
> Do you want me to create a new branch with all my recent fixes squashed into a single commit and base a new PR off that branch?
> Or can I simply push the Ready for review button on this one?

We prefer to have the history of changes over having a "clean" commit history of the master branch. So just clicking on "Ready for review will do".

File: src/USER-BOCS/fix_bocs.cpp (hunk 3 above)
Comment (eagunn) [reply src/USER-BOCS/fix_bocs.cpp]: Of course I can un-do it; that's why I saved it to the bitter end. And why we use version control.
But it's a great idea to clean up the code. And now that I have clang-format working in my IDE, it's the touch of a button to apply whatever rules the team is using.
<humbly>Have I overlooked documentation of the @sjplimp preferences? Is there a list?</humbly>
I wouldn't want to have to apply them manually, but might be able to pare down an .clang-format to apply just what you consider important, as long as I know what those preferences are.

Comment (akohlmey) [reply src/USER-BOCS/fix_bocs.cpp]: > But it's a great idea to clean up the code. And now that I have clang-format working in my IDE, it's the touch of a button to apply whatever rules the team is using.

I have my programming editor (emacs) set up for that, too. Just another set of hot-keys to memorize. ;-)

> Have I overlooked documentation of the @sjplimp preferences? Is there a list?

No. We've been exchanging code for so long, that I have a pretty good idea when I see it, but I could not formalize it. Also, there is some variation. For as long as I don't stray too far, I can have a few things more according to my personal preferences (e.g. I prefer to put a few more explicit curly braces).

> I wouldn't want to have to apply them manually, but might be able to pare down an .clang-format to apply just what you consider important, as long as I know what those preferences are.

This is something that I had planned to work on during my in-person visit at SNL scheduled for this Spring. Unfortunately, that didn't happen and this is best something done in-person (at least the basics). We would then add some ways to automate that during commits, so that all commits could be automatically reformatted.  The long-term goal is to find a compromise that can be used throughout. The clang-format for the unittest branch is meant to be some kind of proof-of-concept.

Comment (eagunn) [reply src/USER-BOCS/fix_bocs.cpp:763]: I have reverted commit b72c1c0eda1, rebuilt, retested, pushed.

In future, I'll be happy to selectively manually reformat in small ways (else braces, etc) as I go. But for now, let's book this code and move on. 

I did briefly investigate applying a minimum-viable-product approach to building up a clang-format yaml file, attempting to apply just a few easily-agreed on rules (2 space indents, no tabs, brace after conditional). But no-go. It's been tried before and is said to be not-compatible with the architecture of the tool: [](https://stackoverflow.com/a/32191189/165164) 

There's a chance that clang-tidy might support that approach. I can look at it for a future set of changes.

**Comment by eagunn** [comment]
@akohlmey My revert has run afoul of your recent utils namespace additions. I'm working on it.

**Comment by eagunn** [comment]
@akohlmey github says merge is block due to a change requested by you. But, as far as I know, I have made all changes requested. I went through and resolved open conversations. But that didn't change the status. 
Is there anything more I need to do? Or do you OK requested changes on your side?

**Comment by akohlmey** [comment]
> @akohlmey github says merge is block due to a change requested by you. But, as far as I know, I have made all changes requested. I went through and resolved open conversations. But that didn't change the status.
> Is there anything more I need to do? Or do you OK requested changes on your side?

I have to approve the pull request to lift the block. Am currently working on #1472 will look through this one after that is done.

**Comment by akohlmey** [comment]
@sjplimp to review/approve this PR, please have a look at #2333 instead, which has the identical content but is displayed correctly.
