### PR TITLE
Redoing groups in compute contact/atom

### LINKED ISSUE #3338: [BUG] Incorrect handling of cross-group interactions in compute contact/atom
**Summary**

Compute contact/atom does not correctly filter cross-group contributions to contact numbers when the compute group-ID is not _all_. When looping through i-j neighbors, the compute filters all contributions where atom i is not in the compute group, seen [here](https://github.com/lammps/lammps/blob/b8acd2e31de3d19ac0a4629ef168e183335bcc74/src/GRANULAR/compute_contact_atom.cpp#L123), and never checks if atom j is a part of the group.

I have a patched copy of compute contact/atom I can submit shortly in a pull request to fix this bug. The patch also adds the ability to limit which groups contribute to the contact number, as can be done in compute coord/atom. 

**LAMMPS Version and Platform**

Current development branch

**Expected Behavior**

From the documentation: "The value of the contact number will be 0.0 for atoms not in the specified compute group."

**Actual Behavior**

When the compute group is not _all_, atoms outside of the compute group may have a non-zero contact number if they are in contact with atoms within the group. Additionally, atoms inside of the compute group may not have the correct contact number if they are in contact with atoms outside of the group.

**Steps to Reproduce**

The attached input script creates a lattice of particles and separates the bottom half into its own group. Using this group, compute contact/atom should return an indentical contact number for every atom in this group (bottom half) and return a value of zero for every atom outside of this group (top half). Instead, atoms on the interface have intermediate contact numbers.

**Further Information, Files, and Links**

[in.contact.txt](https://github.com/lammps/lammps/files/9057246/in.contact.txt)

### PR DESCRIPTION
**Pull request by jtclemm**
**Summary**

This pull request fixes the incorrect cross-group handling incompute contact/atom when the compute group is not _all_ as reported in [issue #3338](https://github.com/lammps/lammps/issues/3338).

While fixing the bug, I also extended the functionality of compute contact/atom to match that of compute coord/atom allowing the user to specify a second group ID. The second ID, defaulted to _all_, restricts which atoms contribute to the contact number. 

**Related Issue(s)**

Fixes [#3338](https://github.com/lammps/lammps/issues/3338).

**Author(s)**

Joel Clemmer (SNL)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

NA

**Implementation Notes**

I debated whether the input arguments should be:
`compute 1 all contact/atom mygroupID` (as implemented)
versus
`compute 1 all contact/atom group mygroupID` (as in compute coord/atom)
I'm not sure which is preferred.

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [x] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

NA

### CODE REVIEW

File: src/GRANULAR/compute_contact_atom.cpp [hunk 1]
```diff
@@ -120,28 +130,28 @@ void ComputeContactAtom::compute_peratom()
...
+      j &= NEIGHMASK;
+
+      delx = xtmp - x[j][0];
+      dely = ytmp - x[j][1];
+      delz = ztmp - x[j][2];
+      rsq = delx * delx + dely * dely + delz * delz;
+      radsum = radi + radius[j];
+      radsumsq = radsum * radsum;
+      if (rsq <= radsumsq) {
+        // Only tally for atoms in compute group (groupbit) if neighbor is in group2 (jgroupbit)
```
Comment (sjplimp) [inline src/GRANULAR/compute_contact_atom.cpp]: Not clear why these mask tests are here, rather than after the j &= NEIGHMASK line.  To avoid computing the distance when the 2 mask values will skip it anyway?

Comment (sjplimp) [reply src/GRANULAR/compute_contact_atom.cpp]: Could also do the mask test on atom i before the j loop, then only one test on atom J inside the j loop, after j is set.

File: doc/src/compute_contact_atom.rst [hunk 2]
```diff
@@ -8,17 +8,19 @@ Syntax
 
 .. parsed-literal::
 
-   compute ID group-ID contact/atom
+   compute ID group-ID contact/atom group2-ID
```
Comment (sjplimp) [inline doc/src/compute_contact_atom.rst:11]: I think this syntax is fine, since its the only option for now

**Review by sjplimp — CHANGES_REQUESTED** [review]
See comments on mask checking

File: src/GRANULAR/compute_contact_atom.cpp (hunk 1 above)
Comment (jtclemm) [reply src/GRANULAR/compute_contact_atom.cpp]: That's a good point, I can filter where i or j are not in either of the two groups to avoid calculating rsq. However, I think the compute will still need the final mask tests before incrementing `contact` to determine which atom(s) are updated. I'll push an update.

File: src/GRANULAR/compute_contact_atom.cpp [hunk 3]
```diff
@@ -115,12 +125,15 @@ void ComputeContactAtom::compute_peratom()
...
+  bool update_i_flag, update_j_flag;
 
   for (i = 0; i < nall; i++) contact[i] = 0.0;
 
   for (ii = 0; ii < inum; ii++) {
     i = ilist[ii];
-    if (mask[i] & groupbit) {
+
+    // Only proceed if i is either part of the compute group or will contribute to contacts
+    if ((mask[i] & groupbit) || (mask[i] & jgroupbit)) {
```
Comment (sjplimp) [inline src/GRANULAR/compute_contact_atom.cpp]: minor point - I would make this if test and the j one below be "continue"
statements so the code is easier to read w/out too deep of nesting

File: src/GRANULAR/compute_contact_atom.cpp [hunk 4]
```diff
@@ -132,15 +145,21 @@ void ComputeContactAtom::compute_peratom()
...
-        radsum = radi + radius[j];
-        radsumsq = radsum*radsum;
-        if (rsq <= radsumsq) {
-          contact[i] += 1.0;
-          contact[j] += 1.0;
+        // Only tally for atoms in compute group (groupbit) if neighbor is in group2 (jgroupbit)
+        update_i_flag = (mask[i] & groupbit) && (mask[j] & jgroupbit);
+        update_j_flag = (mask[j] & groupbit) && (mask[i] & jgroupbit);
+
+        if (update_i_flag || update_j_flag) {
```
Comment (sjplimp) [inline src/GRANULAR/compute_contact_atom.cpp]: ditto for this if statement being a continue

**Review by sjplimp — CHANGES_REQUESTED** [review]
just requesting a minor syntax change

File: src/GRANULAR/compute_contact_atom.cpp (hunk 3 above)
Comment (jtclemm) [reply src/GRANULAR/compute_contact_atom.cpp]: Just made the swap. Thanks for the input!

**Review by sjplimp — APPROVED** [review]
