### PR TITLE
Make read_data compatible with files that have lines longer than 256 chars

### LINKED ISSUE #2735: Max line length in read_data
There appears to be a maximum line length permitted in a read_data file of 255 characters. The most recent master branch LAMMPS (8 Apr 2021) will produce the following misleading error message if the line length exceeds this limit: "ERROR: Unexpected empty line in BondCoeffs section (src/read_data.cpp:1829)" The most recent unstable branch LAMMPS (8 Apr 2021) produces a segmentation fault.

The error can be reproduced by adding characters to the dreiding example:
```
diff  examples/dreiding/data.dreiding examples/dreiding/data.dreiding_error
29c29
<     1             350            1.42 # O_3 C_3
---
>     1             350            1.42 # O_3 C_3 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaeaaaaaaaaaaaaaaaaa
```

I dug around the manual and didn't see a reference to a maximum line length in a read_data file, perhaps it could be added to the manual. It could also be helpful to users if the error message indicated the cause was a line that was too long.

I'm currently converting a data file to LAMMPS format and trying to retain as much of the parameter provenance as  comments in the file, which is causing the lines to exceed the limit in some cases.

### PR DESCRIPTION
**Pull request by akohlmey**
**Summary**

The read data command currently has a compile time line length limit of 256 characters. While that is plenty, it can cause problems when lengthy comments are added. Those will lead to  parser errors, since only the first part of that long line is read and then reading continues. So the comment becomes the first part of the next line and that will lead to parser errors and too many lines per section.

This PR adds a new utility function `utils::fgets_trunc_nl()` which will read data up to the given buffer size and make certain it is NULL terminated and has a newline at the end. But it will keep reading long lines until the actual end of the line is reached.
That data is ignored. This function replaces `fgets()` in `utils::read_lines_from_file()` (which will become simpler since newline is guaranteed by the new function). There are possible other applications in text and potential reader classes.

**Related Issue(s)**

Closes #2735 

**Author(s)**

Axel Kohlmeyer, Temple U

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

All unit tests pass.

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [x] Suitable tests have been added to the unittest tree.

### CODE REVIEW

File: src/utils.cpp [hunk 1]
```diff
@@ -165,6 +165,42 @@ const char *utils::guesspath(char *buf, int len, FILE *fp)
   return buf;
 }
 
+// read line into buffer. if line is too long keep reading until EOL or EOF
+// but return only the first part with a newline at the end.
+
+char *utils::fgets_trunc_nl(char *buf, int size, FILE *fp)
```
Comment (rbberger) [inline src/utils.cpp:171]: I would just call this `fgets_trunc` without the `nl`. First of all it reads like `n1` and it doesn't add new information compared to the default behavior of `fgets`.

Comment (akohlmey) [reply src/utils.cpp:171]: > I would just call this `fgets_trunc` without the `nl`. First of all it reads like `n1` and it doesn't add new information compared to the default behavior of `fgets`.

I agree on the n1/nl thing, but it **does** indicate an additional difference in behavior. `fgets()` will add the terminating NULL, but this function **also** guarantees a newline character at the end. (which is what was initially injected by `utils::read_lines_from_file()` into the block of lines that is then broadcast so it can be split and parsed concurrently on all MPI ranks)

**Review by sjplimp — APPROVED** [review]

File: src/utils.cpp (hunk 1 above)
Comment (akohlmey) [reply src/utils.cpp]: made the rename

**Review by rbberger — APPROVED** [review]
