### PR TITLE
Collected small fixes

### LINKED ISSUE #4937: fix ttm/mod "Missing line in ttm/mod parameter potential file" error in lammps-11Feb2026
Hello LAMMPS developers,
I am performing irradiation simulation on Hf₀.₅Zr₀.₅O₂ (HZO) using fix ttm/mod in the 2026 develop branch, and I keep getting the following error:
ERROR on proc 0: Missing line in ttm/mod parameter potential file! (src/potential_file_reader.cpp:178)
ERROR on proc 0: Missing line in ttm/mod parameter potential file! (src/potential_file_reader.cpp:178)
 (src/EXTRA-FIX/fix_ttm_mod.cpp:534)
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0

clear
units           metal
atom_style      atomic
dimension       3
boundary        p p p
timestep        0.0001

read_data       relax_final_m.data
reset_timestep  0

mass 1 15.999       # O
mass 2 91.224       # Zr
mass 3 178.49       # Hf

pair_style      hybrid/overlay table linear 480 zbl 2.0 5.0
pair_coeff 1 1 table tables/OO.table OO 5.0
pair_coeff 2 2 table tables/ZrZr.table ZrZr 5.0
pair_coeff 3 3 table tables/HfHf.table HfHf 5.0
pair_coeff 1 2 table tables/ZrO.table ZrO 5.0
pair_coeff 1 3 table tables/HfO.table HfO 5.0
pair_coeff 2 3 table tables/HfZr.table HfZr 5.0

pair_coeff 1 1 zbl 8 8
pair_coeff 2 2 zbl 40 40
pair_coeff 3 3 zbl 72 72
pair_coeff 1 2 zbl 8 40
pair_coeff 1 3 zbl 8 72
pair_coeff 2 3 zbl 40 72

neighbor 2.0 bin
neigh_modify every 1 delay 0 check yes

# ==========================
# PKA 设置
# ==========================
variable typeid  equal 5
variable n       equal 15.999
variable pkaE    equal 1000
variable theta   equal 90
variable fei     equal 0

group pka id ${typeid}
group HfO2 type 1 2 3

compute simutem HfO2 temp/com

variable vel equal 4389.077*sqrt(v_pkaE/(1000*v_n))
variable vx equal v_vel*sin(PI*${theta}/180)*cos(PI*${fei}/180)
variable vy equal v_vel*sin(PI*${fei}/180)*sin(PI*${theta}/180)
variable vz equal v_vel*cos(PI*${theta}/180)

fix 1 all nve
velocity pka set ${vx} ${vy} ${vz} units box

# ==========================
# TTM 
# ==========================
fix 2T all ttm/mod 2165418 HfO2_TTM.txt 5 5 5 set 300.0

fix 2 thermostat temp/rescale 1 300 300 1 0.05
fix_modify 2 temp simutem

thermo 50
thermo_style custom step temp pe ke etotal
dump 1 all atom 50 dump.pka.lammpstrj

run 20000

My parameter file (HfO2_TTM.txt):
plaintext
# a0
1e13
# a1
0.0
# a2
0.0
# a3
0.0
# a4
0.0
# C0
200.0
# A
0.0
# rho_e
1e29
# D_e
9.11e-31
# gamma_p
1e-14
# gamma_s
100.0
# v0
0.0
# I0
0.0
# lsurface
0
# rsurface
0
# lskin
0.0
# tau
300.0
# B
0.0
# lambda
0.0
# n_ion
0.0
# surface_movement
0
# T_e_min
0.0
My questions:
Is this parameter file format correct for fix ttm/mod in the 2026 develop branch?
Why does LAMMPS report "Missing line" even though all lines are present?
What is the correct parameter file format for the current develop version?
Thank you for your help!

### PR DESCRIPTION
**Pull request by akohlmey**
**Summary**

This pull request contains multiple small changes and fixes that don't warrant pull requests of their own.

**Related Issue(s)**

Fixes #4937 

**Author(s)**

Axel Kohlmeyer, Temple U

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Artificial Intelligence (AI) Tools Usage**

By submitting this pull request, I confirm that I did NOT use any AI tools to generate
all or parts of the code and modifications in this pull request.

**Backward Compatibility**

N/A

**Implementation Notes**

The following individual changes are included:
- a lot of programming style updates suggested by clang static analyzer after upgrading the static analyzer software to the latest version
- synchronize code between fix_nh.cpp and fix_nh_omp.cpp to be consistent and address issues flagged by coverity scan
- set flag in fix ttm/mod parameter file reader to treat comments as regular text, so that it correctly ignores the lines that the documentation says it does
- update flatpak settings to build LAMMPS-GUI against Qt 6.10, remove GPU package and add KOKKOS/OpenMP and APIP packages instead

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.

### CODE REVIEW

File: src/MBX/fix_mbx.cpp [hunk 1]
```diff
@@ -1469,10 +1433,10 @@ void FixMBX::mbx_init_local()
   mbx_impl->ptr_mbx_local->SetPeriodicity(!domain->nonperiodic);
 
   std::vector<int> egrid = mbx_impl->ptr_mbx_local->GetFFTDimensionElectrostatics(1);
-  std::vector<int> dgrid =
-      mbx_impl->ptr_mbx_local->GetFFTDimensionDispersion(1);    // will return mesh even for gas-phase
+  std::vector<int> dgrid = mbx_impl->ptr_mbx_local->GetFFTDimensionDispersion(
```
Comment (jtclemm) [inline src/MBX/fix_mbx.cpp]: Mistaken line break?

Comment (akohlmey) [reply src/MBX/fix_mbx.cpp]: clang-format quirk

Comment (akohlmey) [reply src/MBX/fix_mbx.cpp]: it doesn't like comments at the end of long lines

**Review by jtclemm — APPROVED** [review]
Phew lot of changes. I couldn't make heads or tails of some of the edits in scalable_font.cpp, but other than that everything looked good to me.

**Comment by akohlmey** [comment]
> I couldn't make heads or tails of some of the edits in scalable_font.cpp

That is mostly just a change in indentation because I moved some local functions into an anonymous namespace to reduce their visibility.

**Comment by jtclemm** [comment]
> > I couldn't make heads or tails of some of the edits in scalable_font.cpp
> 
> That is mostly just a change in indentation because I moved some local functions into an anonymous namespace to reduce their visibility.

I was thinking more like these changes:

503     -           m = ((i << 8) * (x << 8) / (w << 8)) >> 8;
504     -           if (ra[o + m] < 0xF0) {
440     +           m = ((i << 8) * (a << 8) / (w << 8)) >> 8;
441     +          if (raw[o + (m >> 3)] & (1 << (m & 7))) {

But this might be git failing to correctly align the comparison.

**Comment by akohlmey** [comment]
> But this might be git failing to correctly align the comparison.

That is exactly the case here. 

That code is rather obscure. It was designed for embedded devices and is by far the smallest portable font rasterizer that I found. I've stripped it of all features we don't need and made it C++ compatible, so it is probably more cryptic now than it originally was.

It is quite impressive: 180kB source code including the font file and 220kB compiled object code. Freetype is nearly 1MB just for the compiled library.
