### PR TITLE
Collected small changes

### LINKED ISSUE #4713: [BUG] Kokkos is out-of-date for CUDA 13
**Summary**

The version of Kokkos currently packaged in LAMMPS is out date for CUDA 13.0 and will not compile. See Kokkos PR https://github.com/kokkos/kokkos/pull/8298

**LAMMPS Version and Platform**

Tested with latest LAMMPS develop, 1db2e9

**Expected Behavior**

LAMMPS compiles with Kokkos enabled with CUDA 13.0

**Actual Behavior**

If you compile using `lib/kokkos/bin/nvcc_wrapper`, you get an unsupported sm error since `nvcc_wrapper` uses `sm_70` by default which is deprecated with CUDA 13
```
-- Check for working CXX compiler: /project/lammps/lib/kokkos/bin/nvcc_wrapper - broken
CMake Error at /usr/local/lib/python3.12/dist-packages/cmake/data/share/cmake-3.31/Modules/CMakeTestCXXCompiler.cmake:73 (message):
  The C++ compiler

    "/project/lammps/lib/kokkos/bin/nvcc_wrapper"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: '/project/lammps/build/CMakeFiles/CMakeScratch/TryCompile-7Mn1Qm'

    Run Build Command(s): /usr/local/bin/ninja -v cmTC_2c8d6
    [1/2] /project/lammps/lib/kokkos/bin/nvcc_wrapper    -o CMakeFiles/cmTC_2c8d6.dir/testCXXCompiler.cxx.o -c /project/lammps/build/CMakeFiles/CMakeScratch/TryCompile-7Mn1Qm/testCXXCompiler.cxx
    FAILED: CMakeFiles/cmTC_2c8d6.dir/testCXXCompiler.cxx.o
    /project/lammps/lib/kokkos/bin/nvcc_wrapper    -o CMakeFiles/cmTC_2c8d6.dir/testCXXCompiler.cxx.o -c /project/lammps/build/CMakeFiles/CMakeScratch/TryCompile-7Mn1Qm/testCXXCompiler.cxx
    nvcc fatal   : Unsupported gpu architecture 'sm_70'
    ninja: build stopped: subcommand failed.
```
If you fix the default architecture in `nvcc_wrapper` to 80 or greater, you'll get errors including this one from changes to various CUDA APIs
```
FAILED: lib/kokkos/core/src/CMakeFiles/kokkoscore.dir/Cuda/Kokkos_CudaSpace.cpp.o
/project/lammps/lib/kokkos/bin/nvcc_wrapper -DKOKKOS_DEPENDENCE -I/project/lammps/build/lib/kokkos/core/src -I/project/lammps/lib/kokkos/core/src -I/project/lammps/build/lib/kokkos -I/project/lammps/lib/kokkos/tpls/desul/include -I/project/lammps/lib/kokkos/tpls/mdspan/include -Xcudafe --diag_suppress=unrecognized_pragma,--diag_suppress=128,--diag_suppress=186 -O2 -g -DNDEBUG -std=c++17 -fPIC -extended-lambda -Wext-lambda-captures-this -arch=sm_90 -fopenmp -MD -MT lib/kokkos/core/src/CMakeFiles/kokkoscore.dir/Cuda/Kokkos_CudaSpace.cpp.o -MF lib/kokkos/core/src/CMakeFiles/kokkoscore.dir/Cuda/Kokkos_CudaSpace.cpp.o.d -o lib/kokkos/core/src/CMakeFiles/kokkoscore.dir/Cuda/Kokkos_CudaSpace.cpp.o -c /project/lammps/lib/kokkos/core/src/Cuda/Kokkos_CudaSpace.cpp
/project/lammps/lib/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.hpp(269): error: argument of type "size_t" (aka "unsigned long") is incompatible with parameter of type "const cudaGraphEdgeData *"
      return cudaGraphAddDependencies(graph, from, to, numDependencies);
                                                       ^

/project/lammps/lib/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.hpp(269): error: too few arguments in function call
      return cudaGraphAddDependencies(graph, from, to, numDependencies);
                                                                      ^

/project/lammps/lib/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.hpp(349): error: no suitable constructor exists to convert from "int" to "cudaMemLocation"
      return cudaMemAdvise(devPtr, count, advice, device);
                                                  ^

/project/lammps/lib/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.hpp(357): error: no suitable constructor exists to convert from "int" to "cudaMemLocation"
      return cudaMemPrefetchAsync(devPtr, count, dstDevice,
                                                 ^

/project/lammps/lib/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.hpp(358): error: argument of type "cudaStream_t" (aka "CUstream_st *") is incompatible with parameter of type "unsigned int"
                                  get_input_stream(stream));
                                  ^
```

**Steps to Reproduce**

Compile with Kokkos enabled and CUDA 13. I used `nvcc_wrapper` as the CXX compiler with `gcc/g++` as my host compiler.

**Further Information, Files, and Links**

### PR DESCRIPTION
**Pull request by akohlmey**
**Summary**

This pull request collect multiple small changes and fixes that do not warrant a pull request of their own.

**Related Issue(s)**

Includes and thus closes #4699 
Fixes #4713

**Author(s)**

Axel Kohlmeyer, Temple U

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

N/A

**Implementation Notes**

The following individual changes are included:
- reorder main chapters of the user's guide part of the manual to have a more logical succession
- update list of examples in manual and sync with README file
- prevent crashes and print an error message when KOKKOS styles are requested without enabling KOKKOS mode
- some more cleanup related to removing multi/old including a couple of else branches that were forgotten to be removed
- make use of C++17 features to use improved data structures and replace custom code (from PR #4699 by @rbberger)
- replace `hashlittle.h/.cpp` with `std::hash()`
- replace `COLVARS/inthash.h/.cpp` with `std::unordered_map`
- update GoogleTest library to version 1.17.0 which requires C++17
- fix off-by-one error in info command output for multi cutoff
- add `lammps_config_has_omp_support()` function to library interface (and derived code) to query compilation status of OpenMP; similar to `lammps_config_has_mpi_support()`.
- fix for extended OpenKIM unit test failure
- documentation fixes for broken links and typos
- improve error messages
- Fix incompatibilities with CUDA 13 runtime API in Kokkos lib (cherry-picked from upstream Kokkos, see https://github.com/kokkos/kokkos/pull/8328)

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [x] Suitable tests have been added to the unittest tree.

### CODE REVIEW

**Review by jrgissing — APPROVED** [review]

File: lib/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.hpp [hunk 1]
```diff
@@ -346,16 +350,27 @@ class CudaInternal {
                                       cudaMemoryAdvise advice,
                                       int device) const {
     if constexpr (setCudaDevice) set_cuda_device();
+#if CUDART_VERSION >= 13000
+    cudaMemLocation loc = {cudaMemLocationTypeDevice, dstDevice};
```
Comment (fglines-nv) [inline lib/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.hpp]:
```suggestion
    cudaMemLocation loc = {cudaMemLocationTypeDevice, device};
```

File: doc/src/Developer_platform.rst [hunk 2]
```diff
@@ -49,6 +49,16 @@ Platform information functions
...
 
+Since we are requiring C++17 to compile LAMMPS, you can also make use of
+the functionality of the `C++ filesystem library
+<https://en.cppreference.com/w/cpp/filesystem.html>`_.  The following
+functions are in part convenience functions or emulate the behavior of
+similar Python functions or Unix shell commands.  Please note that the
+you need to use the ``string()`` member function of the
+`std::filesystem::path class
+<https://en.cppreference.com/w/cpp/filesystem/path.html>`_ to get access
+to the path as C++ string.
```
Comment (jtclemm) [inline doc/src/Developer_platform.rst]: as *a* C++ string?

Comment (akohlmey) [reply doc/src/Developer_platform.rst]: to be perfectly accurate, this would have to be `a C++ string class instance`.

File: src/delete_atoms.cpp [hunk 3]
```diff
@@ -949,19 +936,17 @@ void DeleteAtoms::molring(int n, char *cbuf, void *ptr)
...
   int *dlist = daptr->dlist;
-  std::map<tagint, int> *hash = daptr->hash;
   int nlocal = daptr->atom->nlocal;
   tagint *molecule = daptr->atom->molecule;
 
   // cbuf = list of N molecule IDs from other proc, put them in hash
 
-  hash->clear();
-  for (int i = 0; i < n; i++) (*hash)[list[i]] = 1;
+  std::set<tagint> hash(list, list + n);
```
Comment (jtclemm) [inline src/delete_atoms.cpp]: I'm curious, is there an advantage to set over unordered_set here?

Recognizing that this doesn't have to be a very performant section of code.

Comment (akohlmey) [reply src/delete_atoms.cpp]: Probably not.

Comment (akohlmey) [reply src/delete_atoms.cpp]: On the contrary, unordered_set should have constant time lookups, while set is n*log(n) since it usually implemented with a red-black tree.

File: src/velocity.cpp [hunk 4]
```diff
@@ -78,7 +78,7 @@ void Velocity::command(int narg, char **arg)
   else if (strcmp(arg[1],"scale") == 0) style = SCALE;
   else if (strcmp(arg[1],"ramp") == 0) style = RAMP;
   else if (strcmp(arg[1],"zero") == 0) style = ZERO;
-  else error->all(FLERR,"Unknown velocity keyword: {}", arg[1]);
+  else error->all(FLERR, 1, "Unknown velocity command style: {}", arg[1]);
```
Comment (jtclemm) [inline src/velocity.cpp:81]: Should this be `all(FLERR, 2, ..., arg[1])`? I get mixed up whether the 2nd argument is 0- or 1-indexed.

Edit: looked this up, I see zero.

File: src/respa.cpp [hunk 5]
```diff
@@ -135,7 +138,7 @@ Respa::Respa(LAMMPS *lmp, int narg, char **arg) :
       }
       ++iarg;
     } else
-      error->all(FLERR, "Illegal run_style respa command");
+      error->all(FLERR, iarg + 1, "Unknown run_style respa keyword {}", arg[iarg]);
```
Comment (jtclemm) [inline src/respa.cpp:141]: Now I am confused here (sorry for jumping around), should this be `all(FLERR, iarg, ..., arg[iarg])`?

Trying to get a hold of the new `error->all` arguments.

**Review by jtclemm — APPROVED** [review]

File: src/velocity.cpp (hunk 4 above)
Comment (akohlmey) [reply src/velocity.cpp:81]: It is 0-based.

BTW since 0 is ambiguous (can be a null pointer), you cannot use 0 but have to use Error::ARGZERO.

File: src/respa.cpp (hunk 5 above)
Comment (akohlmey) [reply src/respa.cpp:141]: The number argument after FLERR (which is a string and a number) is the index in the `Input::arg[]` array. Depending on the circumstances, you have to add an offset to the argument used.

In this case the command is "run_style respa <...>" but the argument list handed to the Respa class starts at `Input::arg[2]`. This **is** quite confusing indeed, but it can only be corrected by completely changing how parsing is done in LAMMPS and I don't see that happening for a while.

Comment (jtclemm) [reply src/respa.cpp:141]: Got it, that's helpful. Thanks for the explanation. Hopefully I'll remember this next time it comes around.

Comment (akohlmey) [reply src/respa.cpp:141]: There is some documentation here: https://docs.lammps.org/Developer_notes.html#errors-warnings-and-informational-messages

But - as usual - it can probably be improved. It is always difficult for me to write this, since I know how I implemented it. To *me* it makes sense, even if it may confuse others.

Of course, the whole thing also suffers a bit from being rushed along by Steve asking repeatedly for "just one more thing". ;-)

File: src/delete_atoms.cpp (hunk 3 above)
Comment (jtclemm) [reply src/delete_atoms.cpp]: I assume that's a typo, set is log(n) no? I mostly asked because I don't know of a scenario when set would be preferred. I guess from the name, it must be when order matters.

FWIW, I also noticed a few other sets were used in the changes. But it didn't look like places where performance was key.

Edit: for instance in `group->molring()`, which might be the only other place look up is performed
