### PR TITLE
Collected small changes for the next patch release

### LINKED ISSUE #2078: [BUG]destbufferoverflow in pair_bop.cpp:5308:22
openSUSE found the following error:
```
[  536s]     inlined from 'void LAMMPS_NS::PairBOP::read_table(char*)' at /home/abuild/rpmbuild/BUILD/lammps-patch_5May2020/src/MANYBODY/pair_bop.cpp:5308:22:
[  536s] /usr/include/bits/stdio2.h:260:58: warning: call to '__fgets_chk_warn' declared with attribute warning: fgets called with bigger size than length of destination buffer
[  536s]   return __fgets_chk_warn (__s, __bos (__s), __n, __stream);
[  536s]                                                           ^
```

### LINKED ISSUE #2081: Regression in USER-OMP: allocations too small
**Summary**

The new AtomVec implementation creates a regression with the USER-OMP package. It assumes `comm->nthreads` does not change. In some cases (e.g. no atom style is set), `FixOMP` sets `comm->nthreads` after `AtomVec` is created.

```
$ lmp -in in.balance.kspace -sf omp -pk omp 4
LAMMPS (5 May 2020)
  using 1 OpenMP thread(s) per MPI task
using multi-threaded neighbor list subroutines
set 4 OpenMP thread(s) per MPI task
...
```
In this case, AtomVec will set its local `nthreads` to 1 and FixOMP will change `comm->nthreads` to 4. All `AtomVec::grow` executions will continue with `nthreads == 1`. This eventually leads to a segfault when accessing the force array.

**LAMMPS Version and Platform**

current master

**Expected Behavior**

Memory buffers get allocated for `comm->nthreads == 4`

**Actual Behavior**

Segmentation fault, since allocation happens for `AtomVec::nthread == 1`

**Steps to Reproduce**

```bash
mkdir build
cd build
cmake -D PKG_KSPACE=on -D PKG_USER-OMP=on ../cmake
make
LAMMPS_BINARY=$PWD/lmp
cd ../examples/balance/
$LAMMPS_BINARY -in in.balance.kspace -sf omp -pk omp 4
```

**Workaround**

1. Add `atom_style` to input script
OR
2. Change all mentions of `nthreads` in atom_vec.cpp to `comm->nthreads`

### PR DESCRIPTION
**Pull request by akohlmey**
**Summary**

The PR collects multiple small changes that do not warrant pull requests of their own.

**Related Issues**

Avoids false positive reported in and thus closes #2078
Addresses the issue reported in and thus closes #2081 

**Author(s)**

Axel Kohlmeyer (Temple U)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

No known issues

**Implementation Notes**

This PR contains the following changes:
- remove unused variables left from AtomVec refactoring in PR #1788 
- address uninitialized variable access due to shadow variable declaration introduced by PR #1788 
- handle the case of `comm->nthreads` changing after the atom style was defined. (#2081)
- fix "use after delete" bug in uloop variable handling
- avoid false positive reports from `-D_FORTIFY_SOURCE` feature (#2078)
- small update/correct for KOKKOS related docs about JIT compilation and UVM

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system

### CODE REVIEW

File: src/atom_vec.cpp [hunk 1]
```diff
@@ -214,30 +214,30 @@ void AtomVec::grow(int n)
     cols = mgrow.cols[i];
     if (datatype == DOUBLE) {
       if (cols == 0)
-        memory->grow(*((double **) pdata),nmax*threads[i],"atom:dvec");
+        memory->grow(*((double **) pdata),nmax*(threads[i]?nthreads:1),"atom:dvec");
```
Comment (rbberger) [inline src/atom_vec.cpp:217]: How about moving `nthreads` into the loop and setting it to 1 `if !threads[0] == false`. That way you avoid multiple `COND ? true-expr : false-expr` constructs

Comment (akohlmey) [reply src/atom_vec.cpp:217]: i don't think it can be avoided, since any threads[i] entry may be true or false. see https://github.com/lammps/lammps/pull/2080/files#diff-5b00f9a402c86c8735a80d7067e68582R2390

Comment (rbberger) [reply src/atom_vec.cpp:217]: Sorry, had a typo. Of course you have to check threads[i] for each loop iteration. What I mean is that for each iteration you don't have to duplicate that check X times, just have the result set once.

Comment (rbberger) [reply src/atom_vec.cpp:217]:
```
for (int i = 0; i < ngrow; i++) {
   const int nthreads = threads[i] ? nthreads : 1;
   ...
}
```

Comment (akohlmey) [reply src/atom_vec.cpp:217]: ok. it doesn't make a difference in terms of performance, since only one of the tests is run per iteration, but it improves readability.
